# Generated by Django 2.2.24 on 2022-01-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storetask',
            name='is_sync',
            field=models.BooleanField(default=False, verbose_name='Обновлено'),
        ),
    ]
