# Generated by Django 2.2.24 on 2022-01-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0002_storetask_is_sync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='iceman/stores/photos/%Y/%m/%d/', verbose_name='Изображение магазина'),
        ),
        migrations.AlterField(
            model_name='storedocument',
            name='file',
            field=models.ImageField(upload_to='iceman/stores/documents/%Y/%m/%d/', verbose_name='Изображение документа'),
        ),
    ]
