# Generated by Django 2.2.24 on 2022-01-24 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0176_task_application'),
        ('iceman', '0004_storetask_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='storetask',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iceman_store_task_region', to='survey.Region', verbose_name='Регион'),
        ),
    ]
