# Generated by Django 2.2.24 on 2022-01-26 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0005_storetask_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=True, verbose_name='Is public')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
                'db_table': 'iceman_regions',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='store',
            name='inn_region',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='store',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iceman_store_region', to='iceman.Region', verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='storetask',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iceman_store_task_region', to='iceman.Region', verbose_name='Регион'),
        ),
    ]
