# Generated by Django 2.2.24 on 2022-01-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0007_region_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='short_name_2',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Короткое название'),
        ),
    ]
