# Generated by Django 2.2.24 on 2022-01-26 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0008_region_short_name_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iceman.Stock', verbose_name='Склад'),
        ),
    ]
