# Generated by Django 2.2.24 on 2022-01-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0010_region_name_1c'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='name_1c',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Название в 1с'),
        ),
    ]
