# Generated by Django 2.2.24 on 2022-01-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0011_auto_20220130_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='name_1c_2',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Название в 1с'),
        ),
    ]
