# Generated by Django 2.2.24 on 2022-02-03 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0012_region_name_1c_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storetask',
            name='is_sales',
        ),
    ]
