# Generated by Django 2.2.24 on 2022-02-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0014_store_is_agreement_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='schedule',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name=''),
        ),
    ]
