# Generated by Django 2.2.24 on 2022-02-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0015_store_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='schedule',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Дни доставки'),
        ),
    ]
