# Generated by Django 2.2.24 on 2022-02-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0018_storedocument_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storedocument',
            options={'ordering': ['store_id', 'type', 'number'], 'verbose_name': 'Документ магазина', 'verbose_name_plural': 'Документы магазина'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='source',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True, default='', verbose_name='Адрес доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(verbose_name='Дата доставки'),
        ),
    ]
