# Generated by Django 2.2.24 on 2022-02-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0019_auto_20220210_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('online', 'Онлайн'), ('delay', 'Отсрочка')], max_length=20, null=True, verbose_name='Тип оплаты'),
        ),
    ]
