# Generated by Django 2.2.24 on 2022-02-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0020_auto_20220210_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='code',
            field=models.CharField(max_length=100, verbose_name='Код'),
        ),
    ]
