# Generated by Django 2.2.24 on 2022-02-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0022_auto_20220211_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='count',
            field=models.IntegerField(default=1, verbose_name='Кол-во'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='price_one',
            field=models.FloatField(blank=True, default=0, verbose_name='Цена за ед'),
        ),
    ]
