# Generated by Django 2.2.24 on 2022-02-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0023_auto_20220211_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='task_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ид задачи'),
        ),
    ]
