# Generated by Django 2.2.24 on 2022-02-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0024_order_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bonus',
            field=models.FloatField(default=0, verbose_name='Бонус сотруднику'),
        ),
    ]
