# Generated by Django 2.2.24 on 2022-02-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0025_product_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bonus',
            field=models.FloatField(blank=True, default=0, verbose_name='Бонус сотруднику'),
        ),
    ]
