# Generated by Django 2.2.24 on 2022-02-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0026_auto_20220211_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='online_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер платежа'),
        ),
        migrations.AddField(
            model_name='order',
            name='online_payment_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Статус платежа'),
        ),
        migrations.AddField(
            model_name='order',
            name='online_payment_sum',
            field=models.IntegerField(blank=True, default=0, verbose_name='Сумма платежа'),
        ),
    ]
