# Generated by Django 2.2.24 on 2022-02-13 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0030_order_online_payment_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='online_payment_qr',
            field=models.TextField(blank=True, null=True, verbose_name='QR-код'),
        ),
        migrations.AddField(
            model_name='order',
            name='online_payment_qr_result',
            field=models.TextField(blank=True, null=True, verbose_name='Результат запроса qr кода'),
        ),
    ]
