# Generated by Django 2.2.24 on 2022-02-13 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0031_auto_20220213_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='online_payment_qr_url',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Url страницы с QR-кодом'),
        ),
    ]
