# Generated by Django 2.2.24 on 2022-02-13 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0032_order_online_payment_qr_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='online_payment_qr_file',
            field=models.ImageField(blank=True, null=True, upload_to='iceman/qr/%Y/%m/%d/', verbose_name='Изображение qr-кода'),
        ),
    ]
