# Generated by Django 2.2.24 on 2022-02-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0034_auto_20220221_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='email',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='E-mail отправки заказов'),
        ),
    ]
