# Generated by Django 2.2.24 on 2022-02-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0035_auto_20220221_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='source',
            name='sys_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Системное имя'),
        ),
    ]
