# Generated by Django 2.2.24 on 2022-02-21 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0036_auto_20220221_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=True, verbose_name='Is public')),
                ('order', models.PositiveIntegerField(default=99999999, editable=False)),
                ('unit', models.CharField(max_length=100, verbose_name='Ед. измерения')),
                ('box_count', models.IntegerField(default=1, verbose_name='Кол-во в коробке')),
                ('min_count', models.IntegerField(default=1, verbose_name='Минимальное количество')),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
                ('is_bonus', models.BooleanField(default=True, verbose_name='Бонусный товар')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iceman.Product', verbose_name='Товар')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iceman.Source', verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'db_table': 'iceman_sources_products',
                'ordering': ['source__name', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SourceProductPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_type', models.CharField(db_index=True, max_length=255, verbose_name='Тип цены')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iceman.SourceProduct', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Цена товара',
                'verbose_name_plural': 'Цены товара',
                'db_table': 'iceman_sources_products_prices',
                'ordering': ['product_id', 'price_type'],
                'unique_together': {('product', 'price_type')},
            },
        ),
    ]
