# Generated by Django 2.2.24 on 2022-02-21 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0037_sourceproduct_sourceproductprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='source',
        ),
    ]
