# Generated by Django 2.2.24 on 2022-02-22 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0039_auto_20220221_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceproduct',
            name='is_updated',
            field=models.BooleanField(default=False, verbose_name='Обновлен'),
        ),
    ]
