# Generated by Django 2.2.24 on 2022-02-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0040_sourceproduct_is_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourceproduct',
            name='is_bonus',
            field=models.BooleanField(default=False, verbose_name='Бонусный товар'),
        ),
        migrations.AlterUniqueTogether(
            name='sourceproduct',
            unique_together={('product', 'source')},
        ),
    ]
