# Generated by Django 2.2.24 on 2022-02-23 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0042_auto_20220223_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='online_payment',
            field=models.BooleanField(default=False, verbose_name='Онлайн оплата'),
        ),
    ]
