# Generated by Django 2.2.24 on 2022-02-23 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0044_remove_product_is_bonus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bonus',
        ),
    ]
