# Generated by Django 2.2.24 on 2022-02-23 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0045_remove_product_bonus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductPrice',
        ),
    ]
