# Generated by Django 2.2.24 on 2022-02-23 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0046_delete_productprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='storetask',
            name='barcode',
            field=models.CharField(default='', max_length=15, verbose_name='Штрихкод'),
        ),
        migrations.AddField(
            model_name='storetask',
            name='weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='Вес в граммах'),
        ),
    ]
