# Generated by Django 2.2.24 on 2022-02-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0048_auto_20220223_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='sum_restrict',
            field=models.FloatField(blank=True, default=4000, help_text='Ограничение суммы в рублях при отсрочки. 0 - нет ограничения.', verbose_name='Ограничение суммы в руб.'),
        ),
    ]
