# Generated by Django 2.2.24 on 2022-03-03 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0051_importproducts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importproducts',
            options={'ordering': ['-date_start'], 'verbose_name': 'Product import', 'verbose_name_plural': 'Products imports'},
        ),
        migrations.AlterModelOptions(
            name='importstores',
            options={'ordering': ['-date_start'], 'verbose_name': 'Store import', 'verbose_name_plural': 'Stores imports'},
        ),
    ]
