# Generated by Django 2.2.24 on 2022-03-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0052_auto_20220303_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='partner_email',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='E-mail партнера'),
        ),
        migrations.AddField(
            model_name='source',
            name='partner_fio',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='ФИО партнера'),
        ),
        migrations.AddField(
            model_name='source',
            name='partner_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Название партнера'),
        ),
        migrations.AddField(
            model_name='source',
            name='partner_phone',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Телефон партнера'),
        ),
    ]
