# Generated by Django 2.2.24 on 2022-03-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0053_auto_20220304_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(default='', max_length=15, unique=True, verbose_name='Штрихкод'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=100, verbose_name='Код'),
        ),
    ]
