# Generated by Django 2.2.24 on 2022-03-11 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0057_auto_20220304_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iceman_order_product_order', to='iceman.Order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='storedocument',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iceman_store_document_store', to='iceman.Store', verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='storestock',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iceman_store_stock_store', to='iceman.Store', verbose_name='Магазин'),
        ),
    ]
