# Generated by Django 2.2.24 on 2022-03-11 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0058_auto_20220311_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iceman.Source', verbose_name='Источник'),
        ),
    ]
