# Generated by Django 2.2.24 on 2022-03-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0062_auto_20220313_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_sum_correct',
            field=models.FloatField(blank=True, default=0, verbose_name='Скорректированная сумма заказа'),
        ),
    ]
