# Generated by Django 2.2.24 on 2022-03-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0063_order_payment_sum_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Новый'), (3, 'Оплачен'), (4, 'Отмененный')], default=1, verbose_name='Статус'),
        ),
    ]
