# Generated by Django 2.2.24 on 2022-03-24 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0064_auto_20220324_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='payment_days',
            field=models.IntegerField(default=10, verbose_name='Кол-во дней для оплаты'),
        ),
    ]
