# Generated by Django 2.2.24 on 2022-03-24 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0065_source_payment_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Новый'), (2, 'Оплата просрочена'), (3, 'Оплачен'), (4, 'Отмененный')], default=1, verbose_name='Статус'),
        ),
    ]
