# Generated by Django 2.2.24 on 2022-03-25 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0066_auto_20220324_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iceman.Source', verbose_name='Источник'),
        ),
    ]
