# Generated by Django 2.2.24 on 2022-03-25 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iceman', '0067_order_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='importproducts',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='imports/%Y/%m/%d/', verbose_name='File'),
        ),
        migrations.AddField(
            model_name='importproducts',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iceman_products_import_user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='importstores',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='imports/%Y/%m/%d/', verbose_name='File'),
        ),
        migrations.AddField(
            model_name='importstores',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iceman_stores_import_user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
