# Generated by Django 2.2.24 on 2022-03-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0068_auto_20220325_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='telegram_status',
            field=models.CharField(choices=[('no_need', 'Не нужно'), ('wait', 'Ожидание'), ('sent', 'Отправлено')], default='no_need', max_length=20, verbose_name='Статус отправки telegram'),
        ),
        migrations.AddField(
            model_name='source',
            name='telegram_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Телеграм id отправки заказов'),
        ),
    ]
