# Generated by Django 2.2.24 on 2022-04-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0070_auto_20220404_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=100, verbose_name='Код'),
        ),
    ]
