# Generated by Django 2.2.24 on 2022-04-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0073_store_payment_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='payment_days',
            field=models.IntegerField(default=10, verbose_name='Кол-во дней отсрочки'),
        ),
        migrations.AlterField(
            model_name='store',
            name='payment_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кол-во дней отсрочки'),
        ),
    ]
