# Generated by Django 2.2.24 on 2022-04-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0075_auto_20220410_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('online', 'Онлайн'), ('delay', 'Отсрочка')], max_length=20, null=True, verbose_name='Тип оплаты'),
        ),
    ]
