# Generated by Django 2.2.24 on 2022-04-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0076_auto_20220410_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('fact', 'Факт'), ('delay', 'Отсрочка')], max_length=20, null=True, verbose_name='Тип оплаты'),
        ),
    ]
