# Generated by Django 2.2.24 on 2022-04-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0079_store_sum_restrict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='sum_restrict',
            field=models.FloatField(blank=True, default=0, help_text='Ограничение суммы в рублях при отсрочки. 0 - нет ограничения.', verbose_name='Ограничение суммы в руб.'),
        ),
    ]
