# Generated by Django 2.2.24 on 2022-04-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0082_auto_20220415_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кол-во дней отсрочки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(blank=True, default=0, verbose_name='Сумма'),
        ),
    ]
