# Generated by Django 2.2.24 on 2022-04-15 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0086_auto_20220415_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='delay_text',
            field=models.TextField(default='', verbose_name='Текст отсрочки'),
        ),
        migrations.AddField(
            model_name='source',
            name='fact_text',
            field=models.TextField(default='', verbose_name='Текст оплаты по факту'),
        ),
    ]
