# Generated by Django 2.2.24 on 2022-04-15 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0088_auto_20220415_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='delay_text',
            field=models.TextField(blank=True, default='', help_text='{days} - кол-во дней, {sum} - ограничение суммы', verbose_name='Текст отсрочки'),
        ),
        migrations.AlterField(
            model_name='source',
            name='fact_text',
            field=models.TextField(blank=True, default='', help_text='{discount} - скидка', verbose_name='Текст оплаты по факту'),
        ),
    ]
