# Generated by Django 2.2.24 on 2022-04-26 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0092_auto_20220423_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Новый'), (2, 'Оплата просрочена'), (3, 'Оплачен'), (4, 'Отмененный'), (5, 'Модерация')], default=1, verbose_name='Статус'),
        ),
    ]
