# Generated by Django 2.2.24 on 2022-04-26 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0093_auto_20220426_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='date_create',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата заказа'),
        ),
    ]
