# Generated by Django 2.2.24 on 2022-04-26 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0094_store_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='date_create',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='store',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iceman_store_user', to='survey.User', verbose_name='Пользователь'),
        ),
    ]
