# Generated by Django 2.2.24 on 2022-04-26 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0198_user_taxpayer_bank'),
        ('iceman', '0095_auto_20220426_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_money',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iceman_order_user_money', to='survey.User', verbose_name='Пользователь получения денег'),
        ),
    ]
