# Generated by Django 2.2.28 on 2022-05-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0097_auto_20220426_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_sum',
            field=models.FloatField(blank=True, default=0, verbose_name='Оплачено'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_sum_correct',
            field=models.FloatField(blank=True, default=0, verbose_name='Реализация'),
        ),
    ]
