# Generated by Django 2.2.24 on 2022-06-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0099_auto_20220504_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='task_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Started'), (2, 'Finished'), (3, 'Checked'), (6, 'Pay in Solar'), (4, 'Payed'), (5, 'Denied'), (7, 'Not payed'), (8, 'Temp denied')], null=True, verbose_name='Статус задачи'),
        ),
    ]
