# Generated by Django 2.2.24 on 2022-06-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0101_auto_20220621_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sync_1c',
            field=models.BooleanField(blank=True, null=True, verbose_name='Есть в 1с'),
        ),
        migrations.AddField(
            model_name='order',
            name='sync_1c_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация с 1с'),
        ),
    ]
