# Generated by Django 2.2.28 on 2022-08-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0104_auto_20220817_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_order_task',
            field=models.BooleanField(default=True, verbose_name='Задача продажи'),
        ),
    ]
