# Generated by Django 2.2.28 on 2022-08-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0105_store_is_order_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='storetask',
            name='only_user_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Только для пользователя'),
        ),
    ]
