# Generated by Django 2.2.28 on 2022-08-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0106_storetask_only_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='type',
            field=models.CharField(choices=[('iceman', 'Айсмен'), ('go', 'Городской отдел')], default='iceman', max_length=20, verbose_name='Тип магазина'),
        ),
    ]
