# Generated by Django 2.2.28 on 2022-09-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0110_auto_20220831_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='storetask',
            name='day_of_week',
            field=models.IntegerField(blank=True, null=True, verbose_name='День недели'),
        ),
        migrations.AddField(
            model_name='storetask',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Выполнена'),
        ),
        migrations.AlterField(
            model_name='storetask',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Полностью выполнена'),
        ),
    ]
