# Generated by Django 2.2.28 on 2022-09-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0112_auto_20220904_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='go_telegram_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Телеграм id отправки заказов в ГО'),
        ),
        migrations.AlterField(
            model_name='source',
            name='telegram_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Телеграм id отправки заказов в Айсман'),
        ),
    ]
