# Generated by Django 2.2.28 on 2022-10-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0115_auto_20221005_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='is_entry',
            field=models.BooleanField(blank=True, null=True, verbose_name='Провод'),
        ),
    ]
