# Generated by Django 2.2.28 on 2022-10-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0116_auto_20221005_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('entity', 'Юридическое лицо'), ('individual', 'Физическое лицо')], default='individual', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
