# Generated by Django 2.2.28 on 2022-10-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0117_auto_20221005_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_url',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ссылка на оплату'),
        ),
    ]
