# Generated by Django 2.2.28 on 2022-11-12 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0118_order_payment_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importstores',
            name='user',
        ),
        migrations.RemoveField(
            model_name='importtasks',
            name='user',
        ),
        migrations.DeleteModel(
            name='ImportProducts',
        ),
        migrations.DeleteModel(
            name='ImportStores',
        ),
        migrations.DeleteModel(
            name='ImportTasks',
        ),
    ]
