# Generated by Django 2.2.28 on 2022-11-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0120_stock_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(blank=True, choices=[('iceman', 'Айсмен'), ('go', 'Городской отдел'), ('client', 'Клиентский')], max_length=20, null=True, verbose_name='Тип заказа'),
        ),
        migrations.AlterField(
            model_name='store',
            name='type',
            field=models.CharField(choices=[('iceman', 'Айсмен'), ('go', 'Городской отдел'), ('client', 'Клиентский')], default='iceman', max_length=20, verbose_name='Тип магазина'),
        ),
    ]
