# Generated by Django 2.2.28 on 2022-11-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0122_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
    ]
