# Generated by Django 2.2.28 on 2022-11-16 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0124_auto_20221115_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('sys_name', models.CharField(max_length=255, unique=True, verbose_name='Системное имя')),
            ],
            options={
                'verbose_name': 'Группа документов',
                'verbose_name_plural': 'Группы документов',
                'db_table': 'iceman_documents_groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentGroupDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=True, verbose_name='Is public')),
                ('order', models.PositiveIntegerField(default=99999999, editable=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iceman.Document', verbose_name='Документ')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iceman.DocumentGroup', verbose_name='Группа документов')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документ',
                'db_table': 'iceman_documents_groups_documents',
                'ordering': ['group__name', 'order'],
            },
        ),
    ]
