# Generated by Django 2.2.28 on 2022-11-16 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0126_auto_20221116_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedocument',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iceman_store_document_document', to='iceman.Document', verbose_name='Документ'),
        ),
    ]
