# Generated by Django 2.2.28 on 2022-11-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0127_storedocument_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentgroupdocument',
            name='required',
            field=models.BooleanField(default=True, verbose_name='Обязательно'),
        ),
    ]
