version: '3.3'
services:
  db:
    image: postgis/postgis:12-3.2
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shop_survey
    volumes:
      - appdata:/var/lib/postgresql/data/
  redis:
    image: redis
    ports:
      - "6379:6379"
  shop-survey:
    build: .
    command: bash -c "
      python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
  celery:
    build: .
    command: celery worker -A application -E -B --loglevel=info                  
    volumes:
      - .:/code
    depends_on:
      - redis
volumes:
  appdata: