# Generated by Django 2.1 on 2018-12-30 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('survey', '0013_auto_20181228_0404'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarStaffPayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_payed', models.DateTimeField(auto_now_add=True, verbose_name='Date payed')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='E-mail')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Surname')),
                ('server_code', models.IntegerField(choices=[(100, 'Error'), (1, 'Waiting for confirm'), (2, 'Success'), (3, 'Declined'), (4, 'Refunded'), (5, 'Partially completed')], default=100, verbose_name='Status')),
                ('server_error', models.TextField(blank=True, null=True, verbose_name='Error text')),
                ('server_response', models.TextField(blank=True, help_text='For debugging', null=True, verbose_name='Server response')),
                ('te', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solar_task', to='survey.TasksExecution', verbose_name='Task execution')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'solar_staff_payments',
                'ordering': ['-date_payed'],
            },
        ),
    ]
