# Generated by Django 2.1 on 2019-01-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_staff', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='solarstaffpayments',
            index=models.Index(fields=['server_code'], name='solar_staff_server__710580_idx'),
        ),
        migrations.AddIndex(
            model_name='solarstaffpayments',
            index=models.Index(fields=['server_error'], name='solar_staff_server__47fe93_idx'),
        ),
        migrations.AddIndex(
            model_name='solarstaffpayments',
            index=models.Index(fields=['server_response'], name='solar_staff_server__90eaa2_idx'),
        ),
        migrations.AddIndex(
            model_name='solarstaffpayments',
            index=models.Index(fields=['email'], name='solar_staff_email_17a75d_idx'),
        ),
        migrations.AddIndex(
            model_name='solarstaffpayments',
            index=models.Index(fields=['first_name'], name='solar_staff_first_n_d64576_idx'),
        ),
        migrations.AddIndex(
            model_name='solarstaffpayments',
            index=models.Index(fields=['last_name'], name='solar_staff_last_na_bf544b_idx'),
        ),
    ]
