# Generated by Django 2.1 on 2019-01-17 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0015_auto_20190117_1951'),
        ('solar_staff', '0002_auto_20190109_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarstaffpayments',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solar_order', to='agent.Order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='solarstaffpayments',
            name='te',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solar_task', to='survey.TasksExecution', verbose_name='Task execution'),
        ),
    ]
