# Generated by Django 2.1 on 2019-01-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_staff', '0003_auto_20190117_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarstaffpayments',
            name='sum',
            field=models.FloatField(blank=True, null=True, verbose_name='Sum'),
        ),
    ]
