# Generated by Django 2.1 on 2019-01-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_staff', '0004_solarstaffpayments_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarstaffpayments',
            name='type',
            field=models.IntegerField(choices=[(1, 'Task execution'), (2, 'Order')], default=1, verbose_name='Type'),
        ),
    ]
