# Generated by Django 2.1 on 2019-01-18 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_staff', '0005_solarstaffpayments_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solarstaffpayments',
            name='type',
            field=models.IntegerField(choices=[(1, 'Task execution'), (2, 'Order cashback')], default=1, verbose_name='Type'),
        ),
    ]
