# Generated by Django 2.2.16 on 2020-10-22 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solar_staff_accounts', '0001_initial'),
        ('solar_staff', '0006_auto_20190118_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarstaffpayments',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solar_account', to='solar_staff_accounts.SolarStaffAccount', verbose_name='Account'),
        ),
    ]
