# Generated by Django 2.2.24 on 2021-10-14 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0164_storetaskavail_deleted'),
        ('solar_staff', '0007_solarstaffpayments_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solarstaffpayments',
            options={'ordering': ['-date_payed'], 'verbose_name': 'Payment history', 'verbose_name_plural': 'Payments history'},
        ),
        migrations.AlterField(
            model_name='solarstaffpayments',
            name='type',
            field=models.IntegerField(choices=[(1, 'Task execution'), (2, 'Order cashback'), (3, 'Custom payment')], default=1, verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.FloatField(default=0, verbose_name='Payment sum')),
                ('status', models.IntegerField(choices=[(1, 'New'), (2, 'Pay in Solar'), (3, 'Payed'), (4, 'Error payment')], default=1, verbose_name='Status')),
                ('comment', models.TextField(max_length=1000, verbose_name='Comment')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Date create')),
                ('date_payment', models.DateTimeField(blank=True, null=True, verbose_name='Date create')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.User', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'chl_payments',
                'ordering': ['-date_create'],
            },
        ),
    ]
