# Generated by Django 2.2.24 on 2021-10-14 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0164_storetaskavail_deleted'),
        ('solar_staff', '0008_auto_20211014_1633'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payments',
            new_name='Payment',
        ),
    ]
