# Generated by Django 2.2.24 on 2021-10-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_staff', '0010_payment_ss_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_payment',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date payment'),
        ),
    ]
