# Generated by Django 2.2.28 on 2022-11-15 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iceman_imports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importproducts',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iceman_products_import_user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='importstores',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iceman_stores_import_user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='importtasks',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iceman_tasks_import_user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.CreateModel(
            name='UploadRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='Request date')),
                ('request_method', models.CharField(blank=True, default='', max_length=1000, verbose_name='Request method')),
                ('request_type', models.CharField(blank=True, default='', max_length=1000, verbose_name='Request type')),
                ('request_ip', models.CharField(blank=True, default='', max_length=1000, verbose_name='Request ip')),
                ('request_text', models.TextField(blank=True, default='', verbose_name='Request text')),
                ('request_files', models.TextField(blank=True, default='', verbose_name='Request files')),
                ('request_data_type', models.CharField(blank=True, default='', max_length=100, verbose_name='Request data type')),
                ('request_data_count', models.IntegerField(blank=True, null=True, verbose_name='Request data count')),
                ('processed', models.BooleanField(default=False, verbose_name='Processed')),
                ('result', models.TextField(blank=True, default='', verbose_name='Result')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iceman_upload_requests_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': '1с запрос айсмен',
                'verbose_name_plural': '1с запросы айсмен',
                'db_table': 'iceman_1c_requests',
                'ordering': ['-request_date'],
            },
        ),
    ]
