# Generated by Django 2.2.28 on 2022-11-15 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iceman_imports', '0002_auto_20221115_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iceman_upload_requests_user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
            preserve_default=False,
        ),
    ]
