# Generated by Django 2.2.24 on 2022-05-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('te_id', models.IntegerField(verbose_name='Идентификатор выполненной задачи')),
            ],
            options={
                'verbose_name': 'Проблема распознавания',
                'verbose_name_plural': 'Проблемы распознавания',
                'db_table': 'ai_problems',
                'ordering': ['id'],
            },
        ),
    ]
