# Generated by Django 2.2.28 on 2022-08-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Проект распознавания',
                'verbose_name_plural': 'Проекты распознавания',
                'db_table': 'ai_projects',
                'ordering': ['name', 'id'],
            },
        ),
    ]
