# Generated by Django 2.2.28 on 2022-08-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_aiproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiproject',
            name='is_default',
            field=models.BooleanField(default=True, verbose_name='По умолчанию'),
        ),
    ]
