# Generated by Django 2.2.28 on 2022-08-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_aiproject_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiproject',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='По умолчанию'),
        ),
    ]
