# Generated by Django 2.1 on 2018-10-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='days_of_week',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Days of weeks'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_once',
            field=models.BooleanField(blank=True, default=False, verbose_name='Execution once'),
        ),
        migrations.AddField(
            model_name='order',
            name='per_week',
            field=models.IntegerField(blank=True, choices=[(0, 'Not limited'), (1, 'Once a week'), (2, '2 times per week'), (3, '3 times per week'), (4, '4 times per week'), (5, '5 times per week'), (6, '6 times per week')], default=0, verbose_name='How many times a week'),
        ),
    ]
