# Generated by Django 2.2.28 on 2022-07-21 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('survey', '0228_auto_20220718_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('route', models.CharField(default='', max_length=255, verbose_name='Route name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_schedule_user', to='survey.User', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Расписание пользователя',
                'verbose_name_plural': 'Расписания пользователей',
                'db_table': 'supervisors_users_schedules',
                'ordering': ['date', 'route', 'user__surname', 'user__name'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UserScheduleTaskExecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_code', models.CharField(max_length=100, verbose_name='Store code')),
                ('store_client_name', models.CharField(max_length=100, verbose_name='Store client name')),
                ('store_category_name', models.CharField(max_length=100, verbose_name='Store category name')),
                ('store_address', models.TextField(max_length=500, verbose_name='Store address')),
                ('task_name', models.CharField(max_length=100, verbose_name='Task name')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervisor.UserSchedule', verbose_name='Расписание пользователя')),
                ('te', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.TasksExecution', verbose_name='Task execution')),
            ],
            options={
                'verbose_name': 'Расписание пользователя',
                'verbose_name_plural': 'Расписания пользователей',
                'db_table': 'supervisors_users_schedules_te',
                'ordering': ['schedule__id', 'id'],
            },
        ),
    ]
