# Generated by Django 2.2.28 on 2022-07-21 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscheduletaskexecution',
            name='store_id',
            field=models.IntegerField(verbose_name='Store id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userscheduletaskexecution',
            name='task_id',
            field=models.IntegerField(verbose_name='Task id'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='userscheduletaskexecution',
            unique_together={('task_id', 'store_id', 'schedule')},
        ),
    ]
