# Generated by Django 2.2.20 on 2021-05-05 20:40

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=True, verbose_name='Is public')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('sys_name', models.CharField(max_length=100, unique=True, verbose_name='System name')),
            ],
            options={
                'verbose_name': 'Loyalty department',
                'verbose_name_plural': 'Loyalty departments',
                'db_table': 'loyalty_departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=True, verbose_name='Is public')),
                ('order', models.PositiveIntegerField(default=99999999, editable=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('sys_name', models.CharField(max_length=100, unique=True, verbose_name='System name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('file', models.FileField(blank=True, null=True, upload_to='loyalty/programs/', verbose_name='File')),
                ('url', models.CharField(blank=True, max_length=200, null=True, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Loyalty program',
                'verbose_name_plural': 'Loyalty programs',
                'db_table': 'loyalty_programs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentMenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=True, verbose_name='Is public')),
                ('order', models.PositiveIntegerField(default=99999999, editable=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('value', models.TextField(help_text='Formatting telegram message', verbose_name='Value')),
                ('action', models.TextField(choices=[('show_text', 'Show text')], default='show_text', max_length=20, verbose_name='Value')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loyalty.Department', verbose_name='Loyalty department')),
            ],
            options={
                'verbose_name': 'Loyalty department menu item',
                'verbose_name_plural': 'Loyalty departments menu items',
                'db_table': 'loyalty_departments_menu',
                'ordering': ['department__order', 'order'],
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
