# Generated by Django 2.2.20 on 2021-05-06 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('contact', models.CharField(max_length=255, verbose_name='Contact face')),
                ('phone', models.CharField(max_length=30, verbose_name='Phone')),
                ('address', models.CharField(max_length=1000, verbose_name='Address')),
                ('inn', models.CharField(blank=True, default='', max_length=12, verbose_name='Inn')),
                ('city', models.CharField(blank=True, default='', max_length=255, verbose_name='City')),
                ('loyalty_1c_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='1c code')),
                ('loyalty_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='story_department', to='loyalty.Department', verbose_name='Department')),
                ('loyalty_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='story_program', to='loyalty.Program', verbose_name='Loyalty program')),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
                'db_table': 'loyalty_stores',
                'ordering': ['loyalty_1c_code'],
            },
        ),
    ]
