# Generated by Django 2.2.20 on 2021-05-07 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0003_auto_20210506_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='loyalty_1c_user',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='1c code user'),
        ),
    ]
