# Generated by Django 2.2.20 on 2021-05-07 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0004_store_loyalty_1c_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='loyalty_cashback',
            field=models.FloatField(default=0, verbose_name='Loyalty cashback'),
        ),
        migrations.AddField(
            model_name='store',
            name='loyalty_debt',
            field=models.FloatField(default=0, verbose_name='Loyalty debt'),
        ),
        migrations.AddField(
            model_name='store',
            name='loyalty_fact',
            field=models.FloatField(default=0, verbose_name='Loyalty fact'),
        ),
        migrations.AddField(
            model_name='store',
            name='loyalty_overdue_debt',
            field=models.FloatField(default=0, verbose_name='Loyalty overdue_debt'),
        ),
        migrations.AddField(
            model_name='store',
            name='loyalty_plan',
            field=models.FloatField(default=0, verbose_name='Loyalty plan'),
        ),
        migrations.AddField(
            model_name='store',
            name='loyalty_sumcashback',
            field=models.FloatField(default=0, verbose_name='Loyalty sumcashback'),
        ),
    ]
