# Generated by Django 2.2.20 on 2021-05-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0005_auto_20210507_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='store',
            name='contact',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Contact face'),
        ),
        migrations.AlterField(
            model_name='store',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Phone'),
        ),
    ]
