# Generated by Django 2.2.20 on 2021-05-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0007_auto_20210514_0054'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='departmentmenuitem',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='departmentmenuitem',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='loyalty/menus/', verbose_name='File'),
        ),
        migrations.AddField(
            model_name='departmentmenuitem',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='departmentmenuitem',
            name='action',
            field=models.TextField(choices=[('show_text', 'Show text'), ('debt', 'Receivables')], default='show_text', max_length=20, verbose_name='Value'),
        ),
    ]
