# Generated by Django 2.2.20 on 2021-05-17 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0010_auto_20210516_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentmenuitem',
            name='value',
            field=models.TextField(blank=True, default='', help_text='Formatting telegram message', verbose_name='Value'),
        ),
    ]
