# Generated by Django 2.2.20 on 2021-06-15 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0012_auto_20210517_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(verbose_name='Start date')),
                ('date_end', models.DateField(verbose_name='Start end')),
                ('current', models.BooleanField(default=False, verbose_name='Current period')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loyalty.Program', verbose_name='Loyalty program')),
            ],
            options={
                'verbose_name': 'Loyalty program period',
                'verbose_name_plural': 'Loyalty program periods',
                'db_table': 'loyalty_programs_periods',
                'ordering': ['date_start', 'date_end'],
            },
        ),
    ]
