# Generated by Django 2.2.20 on 2021-06-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0013_programperiod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programperiod',
            name='date_end',
            field=models.DateField(verbose_name='End date'),
        ),
    ]
