# Generated by Django 2.2.20 on 2021-06-16 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0014_auto_20210615_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='telegram_channel_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram channel Id'),
        ),
    ]
