# Generated by Django 2.2.20 on 2021-06-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0016_store_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='price_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Pryce type'),
        ),
    ]
