# Generated by Django 2.2.24 on 2021-11-30 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0003_notification_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='result',
            field=models.TextField(blank=True, default='', verbose_name='Result'),
        ),
    ]
