# Generated by Django 2.2.24 on 2021-12-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0005_auto_20211130_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.TextField(choices=[('important', 'Important message'), ('task', 'Task'), ('act', 'Act')], default='important', max_length=20, verbose_name='Category'),
        ),
    ]
