# Generated by Django 2.1 on 2018-11-16 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_tasksexecution_comments'),
        ('agent', '0004_auto_20181115_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_order', models.DateTimeField(auto_now_add=True, verbose_name='Date order')),
                ('delivery_address', models.CharField(max_length=1000, verbose_name='Delivery address')),
                ('delivery_date', models.DateField(verbose_name='Delivery date')),
                ('sum', models.FloatField(blank=True, default=0, verbose_name='Sum')),
                ('comment', models.TextField(max_length=1000, verbose_name='Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.User', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'agent_orders',
                'ordering': ['-date_order'],
            },
        ),
        migrations.CreateModel(
            name='OrderGood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('unit', models.CharField(max_length=100, verbose_name='Unit')),
                ('price', models.FloatField(verbose_name='Price')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.Brand', verbose_name='Brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.Category', verbose_name='Category')),
                ('good_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent.Good', verbose_name='Source good')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.Order', verbose_name='Order')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.Store', verbose_name='For store')),
            ],
            options={
                'verbose_name': 'Order good',
                'verbose_name_plural': 'Orders goods',
                'db_table': 'agent_orders_goods',
                'ordering': ['-order__date_order', 'id'],
            },
        ),
    ]
