# Generated by Django 2.1 on 2018-11-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0007_auto_20181119_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergood',
            name='sum',
            field=models.FloatField(blank=True, default=0, verbose_name='Sum'),
        ),
        migrations.AlterField(
            model_name='ordergood',
            name='code',
            field=models.CharField(max_length=100, verbose_name='Code'),
        ),
    ]
