# Generated by Django 2.1 on 2018-11-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0008_auto_20181119_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Is popular'),
        ),
    ]
