# Generated by Django 2.1 on 2018-11-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0009_good_is_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='url',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Url'),
        ),
    ]
