# Generated by Django 2.1 on 2019-01-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0012_auto_20190113_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='cashback_percent',
            field=models.FloatField(default=5, verbose_name='Cashback percent'),
        ),
    ]
