# Generated by Django 2.1 on 2019-01-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0013_brand_cashback_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cashback_sum',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Cashback sum'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='cashback_percent',
            field=models.FloatField(default=5, help_text='in %', verbose_name='Cashback percent'),
        ),
    ]
