# Generated by Django 2.1 on 2019-01-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0014_auto_20190117_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='calc_cashback_sum',
            field=models.BooleanField(default=False, verbose_name='Re calc cashback sum'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Payed'), (3, 'Pay in Solar'), (6, 'Payed cashback'), (4, 'Not payed'), (5, 'Finished')], default=1, verbose_name='Status'),
        ),
    ]
