# Generated by Django 2.1 on 2019-01-23 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0017_auto_20190123_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=True, verbose_name='Is public')),
                ('price', models.FloatField(verbose_name='Price')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.City', verbose_name='City')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.Good', verbose_name='Good')),
            ],
            options={
                'verbose_name': 'Good price',
                'verbose_name_plural': 'Good prices',
                'db_table': 'agent_goods_prices',
                'ordering': ['good__name', 'city__name'],
            },
        ),
    ]
