# Generated by Django 2.1 on 2019-02-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0019_auto_20190123_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='email',
            field=models.TextField(blank=True, help_text='Separated by comma', null=True, verbose_name='E-mail sending orders'),
        ),
    ]
