# Generated by Django 2.1 on 2019-02-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0020_city_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='box_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Box count'),
        ),
    ]
