# Generated by Django 2.1 on 2019-07-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0021_good_box_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='is_oeskimo',
            field=models.BooleanField(default=False, verbose_name='Is Oeskimo'),
        ),
    ]
