# Generated by Django 2.1 on 2020-04-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0022_good_is_oeskimo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=True, verbose_name='Is public')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('file', models.FileField(upload_to='agent/schedule/', verbose_name='Schedule file')),
            ],
            options={
                'verbose_name': 'Delivery schedule',
                'verbose_name_plural': 'Delivery schedule',
                'db_table': 'agent_schedules',
                'ordering': ['id'],
            },
        ),
    ]
