# Generated by Django 2.1 on 2020-04-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0023_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='min_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Minimum count'),
        ),
    ]
