# Generated by Django 2.1 on 2020-06-05 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0066_uploadrequests'),
        ('agent', '0024_good_min_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='only_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.User', verbose_name='Only for user'),
        ),
    ]
