# Generated by Django 2.1 on 2020-06-05 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0025_category_only_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='only_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.UserStatus', verbose_name='Only for user'),
        ),
    ]
