# Generated by Django 2.1 on 2020-06-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0026_auto_20200605_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['order'], 'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='good',
            options={'ordering': ['order'], 'verbose_name': 'Good', 'verbose_name_plural': 'Goods'},
        ),
        migrations.AddField(
            model_name='brand',
            name='order',
            field=models.PositiveIntegerField(default=99999999, editable=False),
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=99999999, editable=False),
        ),
        migrations.AddField(
            model_name='good',
            name='order',
            field=models.PositiveIntegerField(default=99999999, editable=False),
        ),
    ]
