# Generated by Django 2.1 on 2020-06-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0027_auto_20200605_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='telegram_channel_status',
            field=models.IntegerField(choices=[(0, 'Not need'), (1, 'Wait'), (2, 'Sent')], default=0, verbose_name='Telegram channel status'),
        ),
    ]
