# Generated by Django 2.1 on 2020-06-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0028_order_telegram_channel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='telegram_channel_status',
            field=models.IntegerField(choices=[(0, 'Not need'), (1, 'Wait'), (2, 'Sent')], default=1, verbose_name='Telegram channel status'),
        ),
    ]
