# Generated by Django 2.1 on 2020-06-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0030_auto_20200607_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='inn_address',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='store',
            name='inn_director_name',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Director name'),
        ),
        migrations.AlterField(
            model_name='store',
            name='inn_director_title',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Director title'),
        ),
        migrations.AlterField(
            model_name='store',
            name='inn_full_name',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Organization full name'),
        ),
        migrations.AlterField(
            model_name='store',
            name='inn_kpp',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='KPP'),
        ),
        migrations.AlterField(
            model_name='store',
            name='inn_name',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Organization name'),
        ),
        migrations.AlterField(
            model_name='store',
            name='inn_ogrn',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='OGRN'),
        ),
        migrations.AlterField(
            model_name='store',
            name='inn_okved',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='OKVED'),
        ),
    ]
