# Generated by Django 2.1 on 2020-06-07 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0031_auto_20200607_2026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['only_user__id', 'order'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
