# Generated by Django 2.1 on 2020-06-07 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0032_auto_20200607_2046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='good',
            options={'ordering': ['category__only_user__id', 'category__order', 'order'], 'verbose_name': 'Good', 'verbose_name_plural': 'Goods'},
        ),
    ]
