# Generated by Django 2.1 on 2020-06-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0033_auto_20200607_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_agreement',
            field=models.BooleanField(default=False, verbose_name='Is agreement'),
        ),
    ]
