# Generated by Django 2.2.14 on 2020-08-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0034_store_is_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='rest',
            field=models.IntegerField(blank=True, null=True, verbose_name='Rest'),
        ),
    ]
