# Generated by Django 2.2.14 on 2020-08-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0035_good_rest'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='from_1c_firm',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Payment firm'),
        ),
        migrations.AddField(
            model_name='order',
            name='from_1c_pay',
            field=models.FloatField(blank=True, null=True, verbose_name='1c pay sum'),
        ),
        migrations.AddField(
            model_name='order',
            name='from_1c_status',
            field=models.CharField(blank=True, choices=[('a', 'Payed'), ('b', 'Bonus'), ('x', 'Canceled')], max_length=1, null=True, verbose_name='1c status'),
        ),
        migrations.AddField(
            model_name='order',
            name='from_1c_sum',
            field=models.FloatField(blank=True, null=True, verbose_name='1c sum'),
        ),
    ]
