# Generated by Django 2.2.14 on 2020-08-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0036_auto_20200803_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='categories',
            field=models.ManyToManyField(related_name='good_categories', to='agent.Category', verbose_name='Categories'),
        ),
    ]
