# Generated by Django 2.2.14 on 2020-08-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0037_good_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='is_processed',
            field=models.BooleanField(default=True, verbose_name='Is processed'),
        ),
    ]
