# Generated by Django 2.2.14 on 2020-08-21 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0038_good_is_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='need_check',
            field=models.BooleanField(default=False, verbose_name='Need check'),
        ),
    ]
