# Generated by Django 2.2.14 on 2020-08-28 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0039_order_need_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergood',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='agent.Order', verbose_name='Order'),
        ),
    ]
