# Generated by Django 2.2.14 on 2020-09-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0041_good_is_not_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='is_not_delete',
            field=models.BooleanField(default=False, verbose_name='Is not delete'),
        ),
    ]
