# Generated by Django 2.2.16 on 2020-10-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0042_auto_20200904_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='is_no_order',
            field=models.BooleanField(default=False, verbose_name='Is no order'),
        ),
    ]
