# Generated by Django 2.2.16 on 2020-10-18 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0044_auto_20201015_2146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['order'], 'verbose_name': 'Super group', 'verbose_name_plural': 'Super groups'},
        ),
    ]
