# Generated by Django 2.2.16 on 2020-10-18 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0045_auto_20201018_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='brand_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Brand'),
        ),
        migrations.AddField(
            model_name='good',
            name='cashback',
            field=models.FloatField(blank=True, default=0, verbose_name='Cashback'),
        ),
        migrations.AddField(
            model_name='good',
            name='manufacturer',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='good',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.Brand', verbose_name='Super group'),
        ),
        migrations.AlterField(
            model_name='ordergood',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.Brand', verbose_name='Super group'),
        ),
    ]
