# Generated by Django 2.2.16 on 2020-10-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0049_order_ss_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Payed'), (3, 'Pay in Solar'), (6, 'Payed cashback'), (4, 'Canceled'), (5, 'Finished'), (6, 'Error payment')], default=1, verbose_name='Status'),
        ),
    ]
