# Generated by Django 2.2.20 on 2021-05-06 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0052_auto_20210506_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='loyalty_1c_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='1c code'),
        ),
    ]
