# Generated by Django 2.2.20 on 2021-05-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0054_auto_20210507_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='loyalty_1c_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='1c code'),
        ),
    ]
