# Generated by Django 2.2.20 on 2021-05-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0055_auto_20210513_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Source 1c'),
        ),
    ]
