# Generated by Django 2.2.20 on 2021-05-13 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0056_city_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='store',
            name='contact',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Contact face'),
        ),
        migrations.AlterField(
            model_name='store',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Phone'),
        ),
    ]
