# Generated by Django 2.2.20 on 2021-06-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0057_auto_20210513_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Store deleted'),
        ),
    ]
