# Generated by Django 2.2.20 on 2021-06-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0058_store_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='loyalty_1c_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='1c code'),
        ),
    ]
