# Generated by Django 2.2.20 on 2021-06-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0059_auto_20210612_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='is_only_text',
            field=models.BooleanField(default=False, verbose_name='Is only text'),
        ),
    ]
