# Generated by Django 2.2.20 on 2021-06-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0014_auto_20210615_1559'),
        ('agent', '0060_good_is_only_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='departments',
            field=models.ManyToManyField(related_name='good_categories_departments', to='loyalty.Department', verbose_name='Departments'),
        ),
    ]
