# Generated by Django 2.2.20 on 2021-06-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0061_category_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='departments',
            field=models.ManyToManyField(blank=True, null=True, related_name='good_categories_departments', to='loyalty.Department', verbose_name='Departments'),
        ),
    ]
