# Generated by Django 2.2.20 on 2021-06-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0064_store_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.BooleanField(default=False, verbose_name='Payment status'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('driver', 'Pay to driver'), ('telegram', 'Pay via telegram')], max_length=20, null=True, verbose_name='Payment type'),
        ),
    ]
