# Generated by Django 2.2.20 on 2021-06-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0065_auto_20210621_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_sum',
            field=models.FloatField(blank=True, null=True, verbose_name='Payment sum'),
        ),
    ]
