# Generated by Django 2.2.20 on 2021-06-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0066_order_payment_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_sum',
            field=models.FloatField(default=0, verbose_name='Payment sum'),
        ),
    ]
