# Generated by Django 2.2.20 on 2021-06-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0067_auto_20210621_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_sum',
            field=models.FloatField(blank=True, default=0, verbose_name='Payment sum'),
        ),
    ]
