# Generated by Django 2.2.20 on 2021-06-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0068_auto_20210621_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=True, verbose_name='Is public')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Date create')),
                ('source', models.CharField(max_length=255, verbose_name='Payment source')),
                ('provider', models.CharField(max_length=255, verbose_name='Payment provider')),
                ('currency', models.CharField(max_length=3, verbose_name='Currency')),
                ('total_amount', models.FloatField(verbose_name='Total amount')),
                ('invoice_payload', models.CharField(max_length=255, verbose_name='Order info')),
                ('telegram_payment_charge_id', models.CharField(max_length=255, verbose_name='Telegram payment id')),
                ('provider_payment_charge_id', models.CharField(max_length=255, verbose_name='Provider payment id')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'agent_payments',
                'ordering': ['-date_create'],
            },
        ),
    ]
