# Generated by Django 2.2.20 on 2021-06-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0070_auto_20210625_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='storecategory',
            name='default',
            field=models.BooleanField(default=False, verbose_name='Default'),
        ),
    ]
