# Generated by Django 2.2.20 on 2021-06-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0071_storecategory_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='store_category',
            field=models.ManyToManyField(blank=True, related_name='good_categories_store_categories', to='agent.StoreCategory', verbose_name='Store category'),
        ),
    ]
