# Generated by Django 2.2.20 on 2021-06-25 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0072_category_store_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='store_category',
            new_name='store_categories',
        ),
    ]
