# Generated by Django 2.2.20 on 2021-06-25 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0073_auto_20210625_1725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
