# Generated by Django 2.2.20 on 2021-06-26 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0075_store_price_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodPriceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=True, verbose_name='Is public')),
                ('price_type', models.CharField(db_index=True, max_length=255, verbose_name='Price type')),
                ('price', models.FloatField(verbose_name='Price')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.Good', verbose_name='Good')),
            ],
            options={
                'verbose_name': 'Good price',
                'verbose_name_plural': 'Good prices',
                'db_table': 'agent_goods_prices_types',
                'ordering': ['good__name', 'price_type'],
                'unique_together': {('good', 'price_type')},
            },
        ),
    ]
