# Generated by Django 2.2.20 on 2021-06-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0076_goodpricetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodpricetype',
            name='is_processed',
            field=models.BooleanField(default=True, verbose_name='Is processed'),
        ),
    ]
