# Generated by Django 2.2.20 on 2021-06-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0077_goodpricetype_is_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='storecategory',
            name='payment_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Payment name'),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='payment_string',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Payment connection string'),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='telegram_channel_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram channel Id'),
        ),
    ]
