# Generated by Django 2.2.20 on 2021-06-27 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0078_auto_20210627_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1000, unique=True, verbose_name='Code')),
                ('is_used', models.BooleanField(default=False, verbose_name='Is user')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_codes_stores', to='agent.Store', verbose_name='Store')),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
                'db_table': 'agent_promo_codes',
                'ordering': ['-is_used', 'code'],
            },
        ),
    ]
