# Generated by Django 2.2.20 on 2021-06-27 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0079_promocode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocode',
            options={'ordering': ['-is_used', 'code'], 'verbose_name': 'Promo code', 'verbose_name_plural': 'Promo codes'},
        ),
    ]
