# Generated by Django 2.2.20 on 2021-06-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0080_auto_20210627_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='Is used'),
        ),
    ]
