# Generated by Django 2.2.20 on 2021-06-27 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0081_auto_20210627_1721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocode',
            options={'ordering': ['id'], 'verbose_name': 'Promo code', 'verbose_name_plural': 'Promo codes'},
        ),
    ]
