# Generated by Django 2.2.24 on 2021-08-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0084_auto_20210627_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='loyalty_cashback_payed',
            field=models.FloatField(default=0, verbose_name='Loyalty cashback payed'),
        ),
        migrations.AddField(
            model_name='store',
            name='loyalty_cashback_to_pay',
            field=models.FloatField(default=0, verbose_name='Loyalty cashback to payed'),
        ),
    ]
