# Generated by Django 2.2.24 on 2021-12-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0085_auto_20210803_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='TinkoffPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Date create')),
                ('terminal_key', models.CharField(max_length=1000, null=True, verbose_name='Terminal key')),
                ('order_id', models.CharField(max_length=1000, null=True, verbose_name='Order id')),
                ('success', models.BooleanField(null=True, verbose_name='Success')),
                ('status', models.CharField(max_length=1000, null=True, verbose_name='Status')),
                ('payment_id', models.CharField(max_length=1000, null=True, verbose_name='Payment id')),
                ('error_code', models.CharField(max_length=1000, null=True, verbose_name='Error code')),
                ('amount', models.CharField(max_length=1000, null=True, verbose_name='Amount')),
                ('card_id', models.CharField(max_length=1000, null=True, verbose_name='Card id')),
                ('pan', models.CharField(max_length=1000, null=True, verbose_name='Pan')),
                ('exp_date', models.CharField(max_length=1000, null=True, verbose_name='Exp date')),
            ],
            options={
                'verbose_name': 'Tinkoff payment',
                'verbose_name_plural': 'Tinkoff payments',
                'db_table': 'agent_payments_tinkoff',
                'ordering': ['-date_create'],
            },
        ),
    ]
