# Generated by Django 2.2.24 on 2021-12-30 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0087_auto_20211229_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='inn_region',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Region'),
        ),
    ]
