# Generated by Django 2.2.24 on 2022-01-30 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0009_region_stock'),
        ('agent', '0088_store_inn_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iceman.Stock', verbose_name='Склад'),
        ),
    ]
