# Generated by Django 2.2.16 on 2020-10-22 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolarStaffAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name')),
                ('salt', models.CharField(max_length=200, verbose_name='Salt value')),
                ('client_id', models.CharField(max_length=200, verbose_name='Client id')),
            ],
            options={
                'verbose_name': 'Solar staff account',
                'verbose_name_plural': 'Solar staff accounts',
                'db_table': 'solar_staff_accounts',
                'ordering': ['name'],
            },
        ),
    ]
