# Generated by Django 2.1 on 2018-09-16 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_task_per_week'),
        ('users', '0002_load_intial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.Task', verbose_name='Only view task'),
        ),
    ]
