# Generated by Django 2.1 on 2018-09-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20180926_1524'),
        ('users', '0003_user_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='task',
        ),
        migrations.AddField(
            model_name='user',
            name='task',
            field=models.ManyToManyField(blank=True, to='survey.Task', verbose_name='Only view task'),
        ),
    ]
