# Generated by Django 2.2.16 on 2021-03-21 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0075_task_customer'),
        ('users', '0004_auto_20180926_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='regions',
            field=models.ManyToManyField(blank=True, to='survey.Region', verbose_name='Regions for reports'),
        ),
    ]
