# Generated by Django 2.2.28 on 2022-09-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_regions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_date_end',
            field=models.BooleanField(default=True, verbose_name='Показывать дату завершения'),
        ),
    ]
