# Generated by Django 2.2.28 on 2022-11-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0119_auto_20221112_1826'),
        ('users', '0007_auto_20220916_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sources',
            field=models.ManyToManyField(blank=True, to='iceman.Source', verbose_name='Source'),
        ),
    ]
