# Generated by Django 2.1 on 2018-08-13 15:22

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=True, verbose_name='Is public')),
                ('order', models.PositiveIntegerField(default=99999999, editable=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('value', models.TextField(help_text='Formatting telegram message', verbose_name='Value')),
            ],
            options={
                'verbose_name': 'Menu item',
                'verbose_name_plural': 'Menu',
                'db_table': 'telegram_menu',
                'ordering': ['order'],
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='String',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='System name')),
                ('category', models.CharField(max_length=255, verbose_name='Category')),
                ('value', models.TextField(help_text='Formatting telegram message', max_length=1000, verbose_name='Value')),
            ],
            options={
                'verbose_name': 'Telegram message/button',
                'verbose_name_plural': 'Telegram messages/buttons',
                'db_table': 'telegram_strings',
                'ordering': ['category', 'name'],
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
