# Generated by Django 2.1 on 2019-11-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name')),
                ('telegram_id', models.IntegerField(unique=True, verbose_name='Telegram id')),
            ],
            options={
                'verbose_name': 'Telegram channel',
                'verbose_name_plural': 'Telegram channels',
                'db_table': 'telegram_channels',
                'ordering': ['name'],
            },
        ),
    ]
