# Generated by Django 2.1 on 2019-11-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Is public'),
        ),
    ]
