# Generated by Django 2.1 on 2019-11-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0004_auto_20191107_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='telegram_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='Telegram id'),
        ),
    ]
