# Generated by Django 2.2.28 on 2022-07-21 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0229_user_type'),
        ('telegram', '0005_auto_20191107_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=255, verbose_name='Module')),
                ('function', models.CharField(max_length=255, verbose_name='Function')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='survey.User', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Process',
                'verbose_name_plural': 'Process',
                'db_table': 'telegram_process',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='ProcessAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(max_length=1000, verbose_name='Value')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram.Process', verbose_name='Process')),
            ],
            options={
                'verbose_name': 'Process attribute',
                'verbose_name_plural': 'Process attributes',
                'db_table': 'telegram_process_attrs',
                'ordering': ['procedure__id', 'id'],
            },
        ),
    ]
