# Generated by Django 2.1 on 2019-06-17 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('sku_id', models.IntegerField(verbose_name='Su id')),
                ('date_update', models.DateTimeField(auto_now_add=True, verbose_name='Date update')),
            ],
            options={
                'verbose_name': 'Inspector good',
                'verbose_name_plural': 'Inspector goods',
                'db_table': 'inspector_goods',
                'ordering': ['name'],
            },
        ),
    ]
