# Generated by Django 2.1 on 2019-06-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='cid',
            field=models.IntegerField(null=True, verbose_name='Customer id'),
        ),
        migrations.AlterField(
            model_name='good',
            name='sku_id',
            field=models.IntegerField(unique=True, verbose_name='Sku id'),
        ),
    ]
