# Generated by Django 2.1 on 2019-06-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0002_auto_20190618_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='cid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Customer id'),
        ),
    ]
