# Generated by Django 2.1 on 2019-11-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0005_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Name')),
                ('internal_id', models.IntegerField(unique=True, verbose_name='Internal id')),
                ('date_update', models.DateTimeField(auto_now_add=True, verbose_name='Date update')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'inspector_categories',
                'ordering': ['name'],
            },
        ),
    ]
