# Generated by Django 2.1 on 2019-11-14 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0006_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectorGood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Name')),
                ('cid', models.CharField(blank=True, max_length=100, null=True, verbose_name='Customer id')),
                ('sku_id', models.IntegerField(unique=True, verbose_name='Sku id')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inspector.Brand', verbose_name='Brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inspector.Category', verbose_name='Category')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inspector.Manufacturer', verbose_name='Manufacturer')),
            ],
            options={
                'verbose_name': 'Inspector good',
                'verbose_name_plural': 'Inspector goods',
                'db_table': 'inspector_all_goods',
                'ordering': ['name'],
            },
        ),
    ]
