# Generated by Django 2.2.20 on 2021-06-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_archivetasksexecutionassortmentbefore'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveTasksExecutionAssortment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avail', models.FloatField(verbose_name='Avail')),
                ('date_start', models.DateTimeField(verbose_name='Date start')),
            ],
            options={
                'db_table': 'archive_tasks_executions_assortment',
                'managed': False,
            },
        ),
    ]
