# Generated by Django 2.2.24 on 2021-08-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_archivetasksexecutionassortment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveTasksExecutionQuestionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('question', models.CharField(max_length=1000, verbose_name='Question text')),
                ('answer', models.CharField(blank=True, default='', max_length=1000, verbose_name='Answer')),
                ('constructor_step_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Step name')),
            ],
            options={
                'db_table': 'archive_tasks_executions_questionnairess',
                'managed': False,
            },
        ),
    ]
