# Generated by Django 2.1 on 2018-09-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20180823_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='per_week',
            field=models.IntegerField(blank=True, choices=[(0, 'Not limited'), (1, 'Once a week'), (2, '2 times per week'), (3, '3 times per week'), (4, '4 times per week'), (5, '5 times per week')], default=0, verbose_name='How many times a week'),
        ),
    ]
