# Generated by Django 2.1 on 2018-09-20 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    #replaces = [('survey', '0004_auto_20180920_1452'), ('survey', '0005_auto_20180920_1528')]

    dependencies = [
        ('survey', '0003_task_per_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=True, verbose_name='Is public')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'chl_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StoreTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_week', models.IntegerField(blank=True, choices=[(0, 'Not limited'), (1, 'Once a week'), (2, '2 times per week'), (3, '3 times per week'), (4, '4 times per week'), (5, '5 times per week'), (6, '6 times per week'), (7, '7 times per week')], default=0, verbose_name='How many times a week')),
                ('days_of_week', models.CharField(blank=True, default='', max_length=100, verbose_name='Days of weeks')),
                ('is_once', models.BooleanField(blank=True, default=False, verbose_name='Execution once')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_task_store', to='survey.Store', verbose_name='Store')),
            ],
            options={
                'verbose_name': 'Задание в магазине',
                'verbose_name_plural': 'Задания в магазинах',
                'db_table': 'chl_stores_tasks',
                'ordering': ['task__name', 'store__client__name', 'store__code'],
            },
        ),
        migrations.AlterField(
            model_name='task',
            name='per_week',
            field=models.IntegerField(blank=True, choices=[(0, 'Not limited'), (1, 'Once a week'), (2, '2 times per week'), (3, '3 times per week'), (4, '4 times per week'), (5, '5 times per week'), (6, '6 times per week'), (7, '7 times per week')], default=0, verbose_name='How many times a week'),
        ),
        migrations.AddField(
            model_name='storetask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_task_task', to='survey.Task', verbose_name='Task'),
        ),
        migrations.AddField(
            model_name='store',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_store', to='survey.Category', verbose_name='Category'),
        ),
        migrations.CreateModel(
            name='StoreTaskGood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stg_good', to='survey.Good', verbose_name='Good')),
            ],
            options={
                'verbose_name': 'Store task good',
                'verbose_name_plural': 'Stores tasks goods',
                'db_table': 'chl_stores_tasks_goods',
                'ordering': ['task__name', 'store__client__name', 'store__code', 'good__name'],
            },
        ),
        migrations.AlterModelOptions(
            name='storetask',
            options={'ordering': ['task__name', 'store__client__name', 'store__code'], 'verbose_name': 'Store task', 'verbose_name_plural': 'Stores tasks'},
        ),
        migrations.AlterField(
            model_name='storetask',
            name='per_week',
            field=models.IntegerField(blank=True, choices=[(0, 'Not limited'), (1, 'Once a week'), (2, '2 times per week'), (3, '3 times per week'), (4, '4 times per week'), (5, '5 times per week'), (6, '6 times per week')], default=0, verbose_name='How many times a week'),
        ),
        migrations.AlterField(
            model_name='task',
            name='per_week',
            field=models.IntegerField(blank=True, choices=[(0, 'Not limited'), (1, 'Once a week'), (2, '2 times per week'), (3, '3 times per week'), (4, '4 times per week'), (5, '5 times per week'), (6, '6 times per week')], default=0, verbose_name='How many times a week'),
        ),
        migrations.AddField(
            model_name='storetaskgood',
            name='store_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stg_store_task', to='survey.StoreTask', verbose_name='Store task'),
        ),
    ]
