# Generated by Django 2.1 on 2018-09-23 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20180920_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storetaskgood',
            name='good',
        ),
        migrations.RemoveField(
            model_name='storetaskgood',
            name='store_task',
        ),
        migrations.DeleteModel(
            name='StoreTaskGood',
        ),
    ]
