# Generated by Django 2.1 on 2018-10-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20180926_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksexecution',
            name='comments',
            field=models.TextField(blank=True, default='', verbose_name='Comments'),
        ),
    ]
