# Generated by Django 2.1 on 2018-12-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_task_is_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksexecution',
            name='distance',
            field=models.FloatField(blank=True, null=True, verbose_name='Distance'),
        ),
        migrations.AddField(
            model_name='tasksexecution',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='tasksexecution',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
    ]
