# Generated by Django 2.1 on 2018-12-28 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_auto_20181220_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksexecution',
            name='comments_internal',
            field=models.TextField(blank=True, default='', help_text='Remains in the system and is visible only to administrators.', verbose_name='Status comments'),
        ),
        migrations.AddField(
            model_name='tasksexecution',
            name='comments_status',
            field=models.TextField(blank=True, default='', help_text='What comes to the user when the status changes', verbose_name='Status comments'),
        ),
        migrations.AlterField(
            model_name='tasksexecution',
            name='comments',
            field=models.TextField(blank=True, default='', help_text='What the user writes', verbose_name='Comments'),
        ),
    ]
