# Generated by Django 2.1 on 2018-12-28 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_auto_20181228_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksexecution',
            name='comments_internal',
            field=models.TextField(blank=True, default='', help_text='Remains in the system and is visible only to administrators.', null=True, verbose_name='Internal comments'),
        ),
        migrations.AlterField(
            model_name='tasksexecution',
            name='comments_status',
            field=models.TextField(blank=True, default='', help_text='What comes to the user when the status changes', null=True, verbose_name='Status comments'),
        ),
    ]
