# Generated by Django 2.1 on 2019-01-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0016_auto_20190109_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_need_solar_staff_reg',
            field=models.BooleanField(default=False, verbose_name='Need Solar staff register'),
        ),
    ]
