# Generated by Django 2.1 on 2019-02-19 19:53

import application.survey.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0018_user_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_banned',
            field=models.BooleanField(default=False, verbose_name='Is banned'),
        ),
        migrations.AlterField(
            model_name='user',
            name='api_key',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='API key'),
        ),
    ]
