# Generated by Django 2.1 on 2019-05-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0020_tasksexecutionassortment'),
    ]

    operations = [
        migrations.AddField(
            model_name='storetask',
            name='hours_end',
            field=models.IntegerField(blank=True, null=True, verbose_name='Hours end'),
        ),
        migrations.AddField(
            model_name='storetask',
            name='hours_start',
            field=models.IntegerField(blank=True, null=True, verbose_name='Hours start'),
        ),
    ]
