# Generated by Django 2.1 on 2019-06-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0022_auto_20190522_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksexecutionimage',
            name='type',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('enter', 'Enter photo'), ('before', 'Photo before work'), ('after', 'Photo after work'), ('check', 'Cass check')], default='undefined', max_length=10, verbose_name='Image type'),
        ),
    ]
