# Generated by Django 2.1 on 2019-06-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0023_tasksexecutionimage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksexecution',
            name='check_type',
            field=models.CharField(choices=[('not_verified', 'Not verified'), ('true', 'Correct check'), ('false', 'Incorrect check')], default='before', max_length=10, verbose_name='Check'),
        ),
        migrations.AddField(
            model_name='tasksexecution',
            name='step',
            field=models.CharField(choices=[('before', 'Photo before'), ('after', 'Photo after'), ('check', 'Photo check'), ('uploaded', 'All photo uploaded')], default='before', max_length=10, verbose_name='Step'),
        ),
    ]
