# Generated by Django 2.1 on 2019-06-13 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0024_auto_20190613_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasksExecutionCheck',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('survey.tasksexecution',),
        ),
        migrations.AlterField(
            model_name='tasksexecution',
            name='check_type',
            field=models.CharField(choices=[('not_verified', 'Not verified'), ('true', 'Correct check'), ('false', 'Incorrect check')], default='before', max_length=12, verbose_name='Check'),
        ),
    ]
