# Generated by Django 2.1 on 2019-06-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0026_auto_20190617_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksexecution',
            name='check_type',
            field=models.CharField(choices=[('not_verified', 'Not verified'), ('true', 'Correct check'), ('false', 'Incorrect check')], default='not_verified', max_length=12, verbose_name='Check'),
        ),
    ]
