# Generated by Django 2.1 on 2019-06-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0027_auto_20190617_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksexecution',
            name='inspector_positions_text',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Positions text'),
        ),
        migrations.AddField(
            model_name='tasksexecution',
            name='inspector_recognize_text',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Recognize message'),
        ),
        migrations.AddField(
            model_name='tasksexecution',
            name='inspector_report_text',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Report'),
        ),
        migrations.AddField(
            model_name='tasksexecution',
            name='inspector_status',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('upload_error', 'Upload error'), ('parse_error', 'Parse error'), ('report_error', 'report error'), ('success', 'Success')], default='undefined', max_length=20, verbose_name='Inspector status'),
        ),
        migrations.AddField(
            model_name='tasksexecution',
            name='inspector_upload_images_text',
            field=models.TextField(blank=True, default='', verbose_name='Upload images message'),
        ),
    ]
