# Generated by Django 2.1 on 2019-06-17 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0028_auto_20190617_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksexecution',
            name='inspector_report_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Report id'),
        ),
        migrations.AlterField(
            model_name='tasksexecution',
            name='inspector_status',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('upload_error', 'Upload error'), ('parse_error', 'Parse error'), ('report_error', 'Report error'), ('report_wait', 'Report waiting'), ('success', 'Success')], default='undefined', max_length=20, verbose_name='Inspector status'),
        ),
    ]
