# Generated by Django 2.1 on 2019-06-17 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0029_auto_20190617_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksexecution',
            name='inspector_error',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Error text'),
        ),
        migrations.AlterField(
            model_name='tasksexecution',
            name='inspector_status',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('upload_error', 'Upload error'), ('parse_error', 'Parse error'), ('report_error', 'Report error'), ('report_wait', 'Report waiting'), ('error', 'Error'), ('success', 'Success')], default='undefined', max_length=20, verbose_name='Inspector status'),
        ),
    ]
