# Generated by Django 2.1 on 2019-06-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0032_auto_20190617_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Code'),
        ),
    ]
