# Generated by Django 2.1 on 2019-07-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0034_auto_20190621_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksexecution',
            name='inspector_is_alert',
            field=models.BooleanField(blank=True, default=False, verbose_name='Inspector alert'),
        ),
    ]
