# Generated by Django 2.1 on 2019-07-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0035_tasksexecution_inspector_is_alert_squashed_0036_auto_20190715_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksexecution',
            name='inspector_re_work',
            field=models.BooleanField(blank=True, default=False, verbose_name='Inspector alert'),
        ),
    ]
