# Generated by Django 2.1 on 2019-07-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0036_tasksexecution_inspector_re_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksexecution',
            name='inspector_is_work',
            field=models.BooleanField(blank=True, default=False, verbose_name='Inspector is work'),
        ),
        migrations.AlterField(
            model_name='tasksexecution',
            name='inspector_re_work',
            field=models.BooleanField(blank=True, default=False, verbose_name='Inspector re work'),
        ),
    ]
