# Generated by Django 2.1 on 2019-07-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0037_auto_20190723_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksexecution',
            name='set_check_verified',
            field=models.BooleanField(blank=True, default=False, verbose_name='Set check verified'),
        ),
    ]
