# Generated by Django 2.1 on 2019-07-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0038_tasksexecution_set_check_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksexecution',
            name='set_check_not_verified',
            field=models.BooleanField(blank=True, default=False, verbose_name='Set check not verified'),
        ),
    ]
