# Generated by Django 2.1 on 2019-07-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0040_tasksexecutionassortmentbefore'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksexecution',
            name='inspector_report_id_before',
            field=models.IntegerField(blank=True, null=True, verbose_name='Report id before'),
        ),
        migrations.AddField(
            model_name='tasksexecution',
            name='inspector_status_before',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('wait', 'Waiting for inspector'), ('upload_error', 'Upload error'), ('parse_error', 'Parse error'), ('report_error', 'Report error'), ('report_wait', 'Report waiting'), ('error', 'Error'), ('success', 'Success parsing')], default='wait', max_length=20, verbose_name='Inspector status before'),
        ),
    ]
