# Generated by Django 2.1 on 2019-08-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0041_auto_20190726_1813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasksexecutionassortmentbefore',
            options={'ordering': ['-task__date_start', 'id'], 'verbose_name': 'Avail assortment before', 'verbose_name_plural': 'Avail assortments before'},
        ),
        migrations.AddField(
            model_name='tasksexecution',
            name='is_auditor',
            field=models.BooleanField(blank=True, default=False, verbose_name='Checked by auditor'),
        ),
    ]
