# Generated by Django 2.1 on 2019-08-13 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0042_auto_20190801_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksexecution',
            name='check_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Check user'),
        ),
    ]
