# Generated by Django 2.1 on 2019-08-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0043_tasksexecution_check_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('default', models.BooleanField(blank=True, default=False, verbose_name='Default')),
                ('work_days', models.IntegerField(blank=True, default=0, verbose_name='Work days')),
                ('tasks_month', models.IntegerField(blank=True, default=0, verbose_name='Tasks month count')),
                ('tasks_count', models.IntegerField(blank=True, default=0, verbose_name='Tasks count all')),
                ('rate', models.FloatField(default=1, verbose_name='Rate')),
            ],
            options={
                'verbose_name': 'Rank',
                'verbose_name_plural': 'Ranks',
                'db_table': 'chl_ranks',
                'ordering': ['name'],
            },
        ),
    ]
