# Generated by Django 2.1 on 2019-08-29 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0045_rank_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.Rank', verbose_name='Rank'),
        ),
    ]
