# Generated by Django 2.1 on 2019-08-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0046_user_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_fixed_rank',
            field=models.BooleanField(default=False, verbose_name='Fixed rank'),
        ),
    ]
