# Generated by Django 2.1 on 2019-10-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0048_tasksexecution_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksexecution',
            name='status',
            field=models.IntegerField(choices=[(1, 'Started'), (2, 'Finished'), (3, 'Checked'), (6, 'Pay in Solar'), (4, 'Payed'), (5, 'Denied'), (7, 'Not payed'), (8, 'Temp denied')], default=1, verbose_name='Status'),
        ),
    ]
