# Generated by Django 2.1 on 2019-10-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0049_auto_20191027_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_only_self_tasks',
            field=models.BooleanField(default=False, verbose_name='Only self tasks'),
        ),
    ]
