# Generated by Django 2.1 on 2019-10-27 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0050_user_is_only_self_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='storetask',
            name='only_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_task_user', to='survey.User', verbose_name='Only user'),
        ),
    ]
