# Generated by Django 2.1 on 2019-11-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0051_storetask_only_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksexecution',
            name='telegram_channel_status',
            field=models.IntegerField(choices=[(0, 'Not need'), (1, 'Wait'), (2, 'Sent')], default=0, verbose_name='Telegram channel status'),
        ),
    ]
