# Generated by Django 2.1 on 2019-11-14 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0007_inspectorgood'),
        ('survey', '0053_storetask_telegram_channel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasksExecutionAssortmentAll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avail', models.FloatField(verbose_name='Avail')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tea_a_good', to='inspector.InspectorGood', verbose_name='Good')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tea_a_task', to='survey.TasksExecution', verbose_name='Task execution')),
            ],
            options={
                'verbose_name': 'Avail assortment all',
                'verbose_name_plural': 'Avail assortments all',
                'db_table': 'chl_tasks_executions_assortment_all',
                'ordering': ['-task__date_start', 'id'],
            },
        ),
    ]
