# Generated by Django 2.1 on 2019-12-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0054_tasksexecutionassortmentall'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='add_days',
            field=models.FloatField(blank=True, null=True, verbose_name='Add days'),
        ),
        migrations.AddField(
            model_name='task',
            name='add_money',
            field=models.FloatField(blank=True, null=True, verbose_name='Add sum'),
        ),
    ]
