# Generated by Django 2.1 on 2019-12-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0055_auto_20191222_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='add_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Add days'),
        ),
    ]
