# Generated by Django 2.1 on 2019-12-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0059_auto_20191223_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_add_money',
            field=models.BooleanField(default=False, verbose_name='Add value'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_remove_money',
            field=models.BooleanField(default=False, verbose_name='Remove value'),
        ),
    ]
