# Generated by Django 2.1 on 2020-05-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0064_auto_20200515_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksexecution',
            name='date_end_user',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date end user'),
        ),
    ]
