# Generated by Django 2.1 on 2020-06-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0066_uploadrequests'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksexecutionimage',
            name='telegram_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Telegram id'),
        ),
    ]
