# Generated by Django 2.1 on 2020-06-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0067_tasksexecutionimage_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksexecutionimage',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Telegram id'),
        ),
    ]
