# Generated by Django 2.2.16 on 2020-10-15 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0069_auto_20200803_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_status_agent', to='survey.UserStatus', verbose_name='User status for agent'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_status', to='survey.UserStatus', verbose_name='User status'),
        ),
    ]
