# Generated by Django 2.2.16 on 2020-10-22 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solar_staff_accounts', '0001_initial'),
        ('survey', '0070_auto_20201015_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ss_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_ss_account', to='solar_staff_accounts.SolarStaffAccount', verbose_name='Solar staff account'),
        ),
    ]
