# Generated by Django 2.2.16 on 2020-10-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0071_task_ss_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='money_source',
            field=models.FloatField(default=0, verbose_name='Sum source'),
        ),
    ]
