# Generated by Django 2.2.16 on 2020-10-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0072_task_money_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksexecution',
            name='money_source',
            field=models.FloatField(default=0, verbose_name='Sum source'),
        ),
    ]
