# Generated by Django 2.2.16 on 2021-02-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0073_tasksexecution_money_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=True, verbose_name='Is public')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Task customer',
                'verbose_name_plural': 'Tasks customers',
                'db_table': 'chl_tasks_customers',
                'ordering': ['name'],
            },
        ),
    ]
