# Generated by Django 2.2.16 on 2021-02-14 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0074_taskcustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_customer', to='survey.TaskCustomer', verbose_name='Task customer'),
        ),
    ]
