# Generated by Django 2.2.20 on 2021-04-24 15:19

import application.survey.models.all
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0075_task_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='api_key',
            field=models.CharField(blank=True, default=application.survey.models.all.gen_key, max_length=32, null=True, unique=True, verbose_name='API key'),
        ),
    ]
