# Generated by Django 2.2.20 on 2021-04-27 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0077_user_status_legal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status_legal',
            field=models.CharField(choices=[('self_employed', 'Self-employed'), ('other', 'Other')], default='other', max_length=100, verbose_name='Legal status'),
        ),
    ]
