# Generated by Django 2.2.20 on 2021-05-19 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0078_auto_20210427_0215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Request date')),
                ('method', models.CharField(blank=True, default='', max_length=1000, verbose_name='Request method')),
                ('body', models.TextField(blank=True, default='', verbose_name='Request text')),
                ('result', models.TextField(blank=True, default='', verbose_name='Result')),
            ],
            options={
                'verbose_name': 'Request',
                'verbose_name_plural': 'Requests',
                'db_table': 'survey_requests',
                'ordering': ['-date'],
            },
        ),
    ]
