# Generated by Django 2.2.20 on 2021-05-19 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0079_request'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadrequests',
            options={'ordering': ['-request_date'], 'verbose_name': '1c request', 'verbose_name_plural': '1c requests'},
        ),
        migrations.AddField(
            model_name='request',
            name='url',
            field=models.TextField(blank=True, default='', verbose_name='Url'),
        ),
    ]
