# Generated by Django 2.2.20 on 2021-06-13 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0080_auto_20210519_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='disable_loyalty',
            field=models.BooleanField(blank=True, default=False, verbose_name='Disable if store in loyalty'),
        ),
    ]
