# Generated by Django 2.2.20 on 2021-06-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0081_task_disable_loyalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='taxpayer_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Taxpayer join date'),
        ),
        migrations.AddField(
            model_name='user',
            name='taxpayer_email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='user',
            name='taxpayer_fio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='FIO'),
        ),
        migrations.AddField(
            model_name='user',
            name='taxpayer_inn',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='INN'),
        ),
        migrations.AddField(
            model_name='user',
            name='taxpayer_passport_num',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Passport num'),
        ),
        migrations.AddField(
            model_name='user',
            name='taxpayer_passport_series',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Passport series'),
        ),
        migrations.AddField(
            model_name='user',
            name='taxpayer_phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='user',
            name='taxpayer_status',
            field=models.BooleanField(default=False, verbose_name='Taxpayer status'),
        ),
    ]
