# Generated by Django 2.2.20 on 2021-06-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0084_user_is_testing'),
    ]

    operations = [
        migrations.AddField(
            model_name='assortment',
            name='count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Count'),
        ),
    ]
