# Generated by Django 2.2.20 on 2021-06-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0086_uploadrequests_request_data_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadrequests',
            name='request_data_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Request data count'),
        ),
    ]
