# Generated by Django 2.2.20 on 2021-06-28 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0087_uploadrequests_request_data_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksexecution',
            name='check_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_tasksexecution', to=settings.AUTH_USER_MODEL, verbose_name='Check user'),
        ),
        migrations.AlterField(
            model_name='tasksexecution',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_tasksexecution', to='survey.Store', verbose_name='Store'),
        ),
        migrations.AlterField(
            model_name='tasksexecution',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_tasksexecution', to='survey.Task', verbose_name='Task'),
        ),
        migrations.AlterField(
            model_name='tasksexecution',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_tasksexecution', to='survey.User', verbose_name='User'),
        ),
    ]
