# Generated by Django 2.2.20 on 2021-06-29 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0089_auto_20210628_1234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasksexecutionimage',
            options={},
        ),
    ]
