# Generated by Django 2.2.20 on 2021-06-29 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0090_auto_20210629_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksexecutionimage',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_tasksexecutionimage_task', to='survey.TasksExecution', verbose_name='Task execution'),
        ),
    ]
