# Generated by Django 2.2.20 on 2021-06-30 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0092_auto_20210630_1328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasksexecutionassortment',
            options={},
        ),
        migrations.AlterField(
            model_name='tasksexecutionassortment',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_tasksexecutionassortment_good', to='survey.Good', verbose_name='Good'),
        ),
        migrations.AlterField(
            model_name='tasksexecutionassortment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_tasksexecutionassortment_task', to='survey.TasksExecution', verbose_name='Task execution'),
        ),
    ]
