# Generated by Django 2.2.20 on 2021-07-02 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0093_auto_20210630_1425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasksexecutionassortment',
            options={'ordering': ['-task__date_start', 'id'], 'verbose_name': 'Avail assortment', 'verbose_name_plural': 'Avail assortments'},
        ),
        migrations.AlterModelOptions(
            name='tasksexecutionassortmentbefore',
            options={'ordering': ['-task__date_start', 'id'], 'verbose_name': 'Avail assortment before', 'verbose_name_plural': 'Avail assortments before'},
        ),
        migrations.AlterModelOptions(
            name='tasksexecutionimage',
            options={'ordering': ['-task__date_start', 'id'], 'verbose_name': 'Confirmation image', 'verbose_name_plural': 'Confirmation images'},
        ),
    ]
