# Generated by Django 2.2.20 on 2021-07-03 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0094_auto_20210702_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, unique=True, verbose_name='Number')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('user_fio', models.CharField(max_length=255, verbose_name='Fio')),
                ('user_inn', models.CharField(max_length=20, verbose_name='INN')),
                ('user_phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('user_email', models.CharField(max_length=255, verbose_name='Fio')),
                ('sum', models.FloatField(verbose_name='Sum')),
                ('date_start', models.DateTimeField(verbose_name='Date start')),
                ('date_end', models.DateTimeField(verbose_name='Date end')),
                ('is_sent_telegram', models.BooleanField(default=False, verbose_name='Sent telegram')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_act_user', to='survey.User', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Act',
                'verbose_name_plural': 'Acts',
                'db_table': 'chl_acts',
                'ordering': ['-date'],
            },
        ),
    ]
