# Generated by Django 2.2.20 on 2021-07-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0095_act'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date end'),
        ),
        migrations.AlterField(
            model_name='act',
            name='date_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date start'),
        ),
        migrations.AlterField(
            model_name='act',
            name='sum',
            field=models.FloatField(blank=True, null=True, verbose_name='Sum'),
        ),
        migrations.AlterField(
            model_name='act',
            name='user_email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fio'),
        ),
        migrations.AlterField(
            model_name='act',
            name='user_fio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fio'),
        ),
        migrations.AlterField(
            model_name='act',
            name='user_inn',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='INN'),
        ),
        migrations.AlterField(
            model_name='act',
            name='user_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone'),
        ),
    ]
