# Generated by Django 2.2.20 on 2021-07-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0096_auto_20210703_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='user_email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='E-mail'),
        ),
    ]
