# Generated by Django 2.2.20 on 2021-07-03 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0097_auto_20210703_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='check_type',
            field=models.CharField(choices=[('not_verified', 'Not verified'), ('true', 'Correct check'), ('false', 'Incorrect check')], default='not_verified', max_length=12, verbose_name='Check'),
        ),
        migrations.AddField(
            model_name='act',
            name='check_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_act_check_user', to=settings.AUTH_USER_MODEL, verbose_name='Check user'),
        ),
        migrations.AddField(
            model_name='act',
            name='set_check_not_verified',
            field=models.BooleanField(blank=True, default=False, verbose_name='Set check not verified'),
        ),
        migrations.AddField(
            model_name='act',
            name='set_check_verified',
            field=models.BooleanField(blank=True, default=False, verbose_name='Set check verified'),
        ),
    ]
