# Generated by Django 2.2.20 on 2021-07-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0099_auto_20210703_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='comment_manager',
            field=models.TextField(blank=True, null=True, verbose_name='Manager comment'),
        ),
        migrations.AddField(
            model_name='act',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Link'),
        ),
    ]
