# Generated by Django 2.2.20 on 2021-07-03 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0100_auto_20210703_1920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='act',
            options={'ordering': ['-number'], 'verbose_name': 'Act', 'verbose_name_plural': 'Acts'},
        ),
    ]
