# Generated by Django 2.2.20 on 2021-07-03 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0101_auto_20210703_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActCheck',
            fields=[
            ],
            options={
                'verbose_name': 'Check act taxpayers',
                'verbose_name_plural': 'Check acts taxpayers',
                'proxy': True,
                'indexes': [],
            },
            bases=('survey.act',),
        ),
    ]
