# Generated by Django 2.2.20 on 2021-07-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0102_actcheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='id_1c',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='act',
            name='number',
            field=models.CharField(max_length=100, verbose_name='Number'),
        ),
    ]
