# Generated by Django 2.2.20 on 2021-07-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0105_auto_20210705_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='date_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date update'),
        ),
    ]
