# Generated by Django 2.2.20 on 2021-07-06 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0108_auto_20210705_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='assortment',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assortment_task', to='survey.Task', verbose_name='Task'),
        ),
    ]
