# Generated by Django 2.2.20 on 2021-07-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0109_assortment_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='id_1c',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='1c id'),
        ),
    ]
