# Generated by Django 2.2.24 on 2021-07-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0112_auto_20210709_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='storetask',
            name='per_month',
            field=models.IntegerField(blank=True, null=True, verbose_name='How many times a month'),
        ),
    ]
