# Generated by Django 2.2.24 on 2021-07-20 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0114_task_new_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskQuestionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=True, verbose_name='Is public')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Questionnaire',
                'verbose_name_plural': 'Questionnaires',
                'db_table': 'chl_tasks_questionnaires',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaskQuestionnaireQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=True, verbose_name='Is public')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('question', models.CharField(max_length=1000, verbose_name='Question text')),
                ('choices', models.TextField(help_text='Comma separated', verbose_name='Choices')),
                ('require', models.BooleanField(default=True, verbose_name='Require')),
            ],
            options={
                'verbose_name': 'Questionnaire question',
                'verbose_name_plural': 'Questionnaires questions',
                'db_table': 'chl_tasks_questionnaires_questions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaskStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=True, verbose_name='Is public')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('step_type', models.CharField(choices=[('photos', 'Photos'), ('comment', 'Comment'), ('questionnaire', 'Questionnaire')], default='photos', max_length=20, verbose_name='Step type')),
                ('photo_inspector', models.BooleanField(blank=True, null=True, verbose_name='Parse photo in inspector')),
                ('photo_check_assortment', models.BooleanField(blank=True, null=True, verbose_name='Check assortment after parse')),
                ('photo_check', models.BooleanField(blank=True, null=True, verbose_name='Check photo by manager')),
                ('require', models.BooleanField(default=True, verbose_name='Require')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_taskstep_questionnaire', to='survey.TaskQuestionnaire', verbose_name='Questionnaire')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_taskstep_task', to='survey.Task', verbose_name='Task')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
