# Generated by Django 2.2.24 on 2021-08-02 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0115_taskquestionnaire_taskquestionnairequestion_taskstep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskquestionnaire',
            name='is_public',
        ),
    ]
