# Generated by Django 2.2.24 on 2021-08-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0117_taskquestionnairequestion_questionnaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskquestionnairequestion',
            name='choices',
            field=models.TextField(help_text='Enter separated', verbose_name='Choices'),
        ),
    ]
