# Generated by Django 2.2.24 on 2021-08-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0118_auto_20210802_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskquestionnairequestion',
            name='order',
            field=models.PositiveIntegerField(default=99999999, editable=False),
        ),
    ]
