# Generated by Django 2.2.24 on 2021-08-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0119_taskquestionnairequestion_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskquestionnairequestion',
            name='question_type',
            field=models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('choices', 'Choices')], default='string', max_length=20, verbose_name='Question type'),
        ),
    ]
