# Generated by Django 2.2.24 on 2021-08-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0121_auto_20210802_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskquestionnairequestion',
            name='choices',
            field=models.TextField(blank=True, default='', help_text='Enter separated', verbose_name='Choices'),
        ),
    ]
