# Generated by Django 2.2.24 on 2021-08-03 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0123_auto_20210802_0956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskquestionnairequestion',
            options={'ordering': ['questionnaire', 'order'], 'verbose_name': 'Questionnaire question', 'verbose_name_plural': 'Questionnaires questions'},
        ),
    ]
