# Generated by Django 2.2.24 on 2021-08-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0124_auto_20210803_1308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskstep',
            options={'ordering': ['task', 'order'], 'verbose_name': 'Task step', 'verbose_name_plural': 'Tasks step'},
        ),
        migrations.AddField(
            model_name='taskstep',
            name='order',
            field=models.PositiveIntegerField(default=99999999, editable=False),
        ),
        migrations.AddField(
            model_name='taskstep',
            name='text',
            field=models.CharField(default=None, max_length=10000, verbose_name='Text'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='taskstep',
            unique_together={('name', 'task')},
        ),
        migrations.AlterModelTable(
            name='taskstep',
            table='chl_tasks_steps',
        ),
    ]
