# Generated by Django 2.2.24 on 2021-08-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0125_auto_20210803_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstep',
            name='photo_check',
            field=models.BooleanField(default=False, verbose_name='Check photo by manager'),
        ),
        migrations.AlterField(
            model_name='taskstep',
            name='photo_check_assortment',
            field=models.BooleanField(default=False, verbose_name='Check assortment after parse'),
        ),
        migrations.AlterField(
            model_name='taskstep',
            name='photo_inspector',
            field=models.BooleanField(default=False, verbose_name='Parse photo in inspector'),
        ),
    ]
