# Generated by Django 2.2.24 on 2021-08-03 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0127_auto_20210803_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstep',
            name='questionnaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_taskstep_questionnaire', to='survey.TaskQuestionnaire', verbose_name='Questionnaire'),
        ),
    ]
