# Generated by Django 2.2.24 on 2021-08-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0128_auto_20210803_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstep',
            name='text',
            field=models.TextField(verbose_name='Text'),
        ),
    ]
