# Generated by Django 2.2.24 on 2021-08-04 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0129_auto_20210803_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksexecution',
            name='constructor_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_tasksexecution_constructor_step', to='survey.TaskStep', verbose_name='Task step'),
        ),
    ]
