# Generated by Django 2.2.24 on 2021-08-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0130_tasksexecution_constructor_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksexecutionimage',
            name='constructor_step_name',
            field=models.CharField(default='', max_length=200, verbose_name='Step name'),
        ),
    ]
