# Generated by Django 2.2.24 on 2021-08-07 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0131_tasksexecutionimage_constructor_step_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasksExecutionQuestionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='Name')),
                ('question_text', models.CharField(max_length=1000, verbose_name='Question text')),
                ('answer', models.CharField(blank=True, default='', max_length=1000, verbose_name='Name')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_tasksexecutionquestionnaire_task', to='survey.TasksExecution', verbose_name='Task execution')),
            ],
            options={
                'verbose_name': 'Task questionnaire answer',
                'verbose_name_plural': 'Task questionnaire answers',
                'ordering': ['-task__date_start', 'id'],
                'unique_together': {('question', 'task')},
            },
        ),
    ]
