# Generated by Django 2.2.24 on 2021-08-08 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0132_tasksexecutionquestionnaire'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tasksexecutionquestionnaire',
            table='chl_tasks_executions_questionnaires',
        ),
    ]
