# Generated by Django 2.2.24 on 2021-08-08 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0133_auto_20210808_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksexecutionquestionnaire',
            name='questionnaire',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='survey_tasksexecutionquestionnaire_questionnaire', to='survey.TaskQuestionnaire', verbose_name='Task questionnaire'),
            preserve_default=False,
        ),
    ]
