# Generated by Django 2.2.24 on 2021-08-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0136_auto_20210808_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksexecutionquestionnaire',
            name='answer',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Answer'),
        ),
    ]
