# Generated by Django 2.2.24 on 2021-08-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0137_auto_20210809_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksexecutionassortment',
            name='constructor_step_name',
            field=models.CharField(default='', max_length=200, verbose_name='Step name'),
        ),
    ]
