# Generated by Django 2.2.24 on 2021-08-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0139_tasksexecutioninspector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksexecutionassortment',
            name='constructor_step_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Step name'),
        ),
        migrations.AlterField(
            model_name='tasksexecutionimage',
            name='constructor_step_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Step name'),
        ),
        migrations.AlterField(
            model_name='tasksexecutioninspector',
            name='constructor_step_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Step name'),
        ),
        migrations.AlterField(
            model_name='tasksexecutionquestionnaire',
            name='constructor_step_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Step name'),
        ),
    ]
