# Generated by Django 2.2.24 on 2021-08-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0140_auto_20210809_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksexecutioninspector',
            name='inspector_is_alert',
            field=models.BooleanField(blank=True, default=False, verbose_name='Inspector alert'),
        ),
    ]
