# Generated by Django 2.2.24 on 2021-08-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0141_tasksexecutioninspector_inspector_is_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksexecutioninspector',
            name='date_start',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date start'),
            preserve_default=False,
        ),
    ]
