# Generated by Django 2.2.24 on 2021-08-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0142_tasksexecutioninspector_date_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksexecutionimage',
            name='constructor_check',
            field=models.BooleanField(blank=True, default=False, verbose_name='Check'),
        ),
    ]
