# Generated by Django 2.2.24 on 2021-09-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0143_tasksexecutionimage_constructor_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sms_attempts',
            field=models.IntegerField(default=0, verbose_name='Number of attempts'),
        ),
        migrations.AddField(
            model_name='user',
            name='sms_code',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Sms code'),
        ),
        migrations.AddField(
            model_name='user',
            name='sms_date',
            field=models.DateTimeField(null=True, verbose_name='Date sms sent'),
        ),
    ]
