# Generated by Django 2.2.24 on 2021-09-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0145_auto_20210906_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Send date')),
                ('phone', models.CharField(max_length=100, unique=True, verbose_name='Phone')),
                ('code', models.CharField(max_length=4, verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Sms',
                'verbose_name_plural': 'Sms',
                'db_table': 'survey_sms',
                'ordering': ['-date'],
            },
        ),
    ]
