# Generated by Django 2.2.24 on 2021-09-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0146_sms'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='text',
            field=models.TextField(default='', verbose_name='Text'),
            preserve_default=False,
        ),
    ]
