# Generated by Django 2.2.24 on 2021-09-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0147_sms_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='response_code',
            field=models.IntegerField(default=200, verbose_name='Response code'),
        ),
        migrations.AddField(
            model_name='sms',
            name='response_text',
            field=models.TextField(default='', verbose_name='Response text'),
        ),
    ]
