# Generated by Django 2.2.24 on 2021-09-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0148_auto_20210906_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='Phone'),
        ),
    ]
