# Generated by Django 2.2.24 on 2021-09-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0152_storetaskavail_is_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storetaskavail',
            name='only_user_id',
            field=models.IntegerField(null=True, verbose_name='Only user id'),
        ),
    ]
