# Generated by Django 2.2.24 on 2021-09-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0153_auto_20210914_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storetaskavail',
            name='store_region_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Store region name'),
        ),
        migrations.AlterField(
            model_name='storetaskavail',
            name='store_task_id',
            field=models.IntegerField(unique=True, verbose_name='Store task id'),
        ),
    ]
