# Generated by Django 2.2.24 on 2021-09-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0155_auto_20210914_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storetaskavail',
            name='only_user_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Only user id'),
        ),
    ]
