# Generated by Django 2.2.24 on 2021-09-14 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0157_storetaskavail_lock_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storetaskavail',
            old_name='lock_user',
            new_name='lock_user_id',
        ),
    ]
