# Generated by Django 2.2.24 on 2021-09-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0158_auto_20210914_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='storetaskavail',
            name='telegram_channel_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram channel id'),
        ),
    ]
