# Generated by Django 2.2.24 on 2021-10-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0159_storetaskavail_telegram_channel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstep',
            name='photo_from_gallery',
            field=models.BooleanField(default=True, verbose_name='Ability to upload photos from the gallery'),
        ),
    ]
