# Generated by Django 2.2.24 on 2021-10-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0160_taskstep_photo_from_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksexecution',
            name='source',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('telegram', 'Telegram'), ('android', 'Android'), ('iphone', 'iPhone')], default='undefined', max_length=20, verbose_name='Source'),
        ),
    ]
