# Generated by Django 2.2.24 on 2021-10-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0161_tasksexecution_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksexecution',
            name='source',
            field=models.CharField(choices=[('undefined', 'Unknown'), ('telegram', 'Telegram'), ('android', 'Android'), ('iphone', 'iPhone')], default='undefined', max_length=20, verbose_name='Source'),
        ),
    ]
