# Generated by Django 2.2.24 on 2021-10-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0162_auto_20211010_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='storetaskavail',
            name='update_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Update time'),
        ),
    ]
