# Generated by Django 2.2.24 on 2021-10-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0163_storetaskavail_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='storetaskavail',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Is deleted'),
        ),
    ]
