# Generated by Django 2.2.24 on 2021-11-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0164_storetaskavail_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='storetaskavail',
            name='store_region_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Store region id'),
        ),
    ]
