# Generated by Django 2.2.24 on 2021-11-30 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0165_storetaskavail_store_region_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_use', models.DateTimeField(auto_now=True, verbose_name='Date use')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('key', models.CharField(max_length=255, verbose_name='Key')),
                ('os', models.CharField(max_length=255, verbose_name='OS')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.User', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Mobile device',
                'verbose_name_plural': 'Mobile devices',
                'db_table': 'telegram_users_devices',
                'ordering': ['-date_use'],
            },
        ),
    ]
