# Generated by Django 2.2.24 on 2021-11-30 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0168_userdevice_date_create'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdevice',
            options={'ordering': ['-date_create'], 'verbose_name': 'Mobile device', 'verbose_name_plural': 'Mobile devices'},
        ),
    ]
