# Generated by Django 2.2.24 on 2021-12-03 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0169_auto_20211130_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevice',
            name='version',
            field=models.CharField(default='', max_length=255, verbose_name='Version'),
        ),
    ]
