# Generated by Django 2.2.24 on 2021-12-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0170_userdevice_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram id'),
        ),
    ]
