# Generated by Django 2.2.24 on 2021-12-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0172_externalrequests'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='route',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Route name'),
        ),
    ]
