# Generated by Django 2.2.24 on 2022-01-18 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0174_user_qlik_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDeviceIceman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Date create')),
                ('date_use', models.DateTimeField(auto_now=True, verbose_name='Date use')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('key', models.CharField(max_length=255, verbose_name='Device key')),
                ('os', models.CharField(max_length=255, verbose_name='OS')),
                ('version', models.CharField(default='', max_length=255, verbose_name='Version')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.User', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Mobile device',
                'verbose_name_plural': 'Mobile devices',
                'db_table': 'iceman_users_devices',
                'ordering': ['-date_create'],
            },
        ),
    ]
