# Generated by Django 2.2.24 on 2022-01-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0175_userdeviceiceman'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='application',
            field=models.CharField(choices=[('shop_survey', 'Сюрвеер'), ('iceman', 'Айсмен')], default='shop_survey', max_length=20, verbose_name='Приложение'),
        ),
    ]
