# Generated by Django 2.2.24 on 2022-01-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0176_task_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksexecution',
            name='inspector_status',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('wait', 'Waiting for inspector'), ('upload_wait', 'Upload wait'), ('upload_error', 'Upload error'), ('parse_error', 'Parse error'), ('report_process', 'Report process'), ('report_error', 'Report error'), ('report_wait', 'Report waiting'), ('error', 'Error'), ('success', 'Success parsing'), ('ai', 'Shop survey AI')], default='wait', max_length=20, verbose_name='Inspector status'),
        ),
        migrations.AlterField(
            model_name='tasksexecution',
            name='inspector_status_before',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('wait', 'Waiting for inspector'), ('upload_wait', 'Upload wait'), ('upload_error', 'Upload error'), ('parse_error', 'Parse error'), ('report_process', 'Report process'), ('report_error', 'Report error'), ('report_wait', 'Report waiting'), ('error', 'Error'), ('success', 'Success parsing'), ('ai', 'Shop survey AI')], default='wait', max_length=20, verbose_name='Inspector status before'),
        ),
    ]
