# Generated by Django 2.2.24 on 2022-01-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0177_auto_20220126_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksexecution',
            name='application',
            field=models.CharField(choices=[('shop_survey', 'Сюрвеер'), ('iceman', 'Айсмен')], default='shop_survey', max_length=20, verbose_name='Source'),
        ),
    ]
