# Generated by Django 2.2.24 on 2022-01-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0178_tasksexecution_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksexecution',
            name='application',
            field=models.CharField(choices=[('shop_survey', 'Сюрвеер'), ('iceman', 'Айсмен')], default='shop_survey', max_length=20, verbose_name='Приложение'),
        ),
    ]
