# Generated by Django 2.2.24 on 2022-02-04 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0179_auto_20220129_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='new_task',
            field=models.BooleanField(default=True, verbose_name='New task with constructor'),
        ),
    ]
