# Generated by Django 2.2.24 on 2022-02-04 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iceman', '0013_remove_storetask_is_sales'),
        ('survey', '0180_auto_20220204_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksexecution',
            name='store_iceman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_tasksexecution_store_iceman', to='iceman.Store', verbose_name='Store'),
        ),
    ]
