# Generated by Django 2.2.24 on 2022-02-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0181_tasksexecution_store_iceman'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.CharField(blank=True, choices=[('default', 'Задание с конструктором'), ('sales', 'Задание продажа'), ('payment', 'Задание оплата')], max_length=20, null=True, verbose_name='Тип задачи'),
        ),
    ]
