# Generated by Django 2.2.24 on 2022-02-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0182_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='money_fix',
            field=models.BooleanField(default=False, verbose_name='Фиксировать сумму'),
        ),
    ]
