# Generated by Django 2.2.24 on 2022-02-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0185_auto_20220222_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksexecutionimage',
            name='md5',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='Md5 sum'),
        ),
    ]
