# Generated by Django 2.2.24 on 2022-03-25 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0187_task_fix_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='fix_status',
            field=models.BooleanField(default=False, help_text='Задачи с фиксированным статусом невозможно менять в интерфейсе администрирования, статус для них меняется автоматически', verbose_name='Фиксировать статус'),
        ),
    ]
