# Generated by Django 2.2.24 on 2022-03-25 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0188_auto_20220325_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksexecution',
            name='source',
            field=models.CharField(choices=[('undefined', 'Unknown'), ('telegram', 'Telegram'), ('android', 'Android'), ('iphone', 'iPhone'), ('admin', 'Админка')], default='undefined', max_length=20, verbose_name='Source'),
        ),
    ]
