# Generated by Django 2.2.24 on 2022-04-09 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0191_auto_20220325_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assortment_1c',
            field=models.BooleanField(default=False, help_text='Если стоит эта галочка, то для этой задачи будет обновляться ассортимент автоматически при выгрузки из 1с', verbose_name='Обновлять ассортимент из 1с'),
        ),
    ]
