# Generated by Django 2.2.24 on 2022-04-13 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0194_remove_task_assortment_1c'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='application',
            field=models.CharField(choices=[('shop_survey', 'Сюрвеер'), ('iceman', 'Айсмен'), ('classic_logistic', 'Классик логистика'), ('smoroza', 'Смороза Биз'), ('samberu', 'Самберу'), ('logistic_msk', 'Логистика МСК'), ('promotion', 'Продвижение'), ('classic_logistic_2', '2 Классик логистика'), ('logistic_msk_2', '2 Логистика МСК')], default='shop_survey', max_length=20, verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='tasksexecution',
            name='application',
            field=models.CharField(choices=[('shop_survey', 'Сюрвеер'), ('iceman', 'Айсмен'), ('classic_logistic', 'Классик логистика'), ('smoroza', 'Смороза Биз'), ('samberu', 'Самберу'), ('logistic_msk', 'Логистика МСК'), ('promotion', 'Продвижение'), ('classic_logistic_2', '2 Классик логистика'), ('logistic_msk_2', '2 Логистика МСК')], default='shop_survey', max_length=20, verbose_name='Проект'),
        ),
    ]
