# Generated by Django 2.2.24 on 2022-04-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0195_auto_20220413_0159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=True, verbose_name='Is public')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'User status',
                'verbose_name_plural': 'User statuses',
                'db_table': 'chl_banks',
                'ordering': ['name'],
            },
        ),
    ]
