# Generated by Django 2.2.28 on 2022-05-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0198_user_taxpayer_bank'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Причина отсутствия',
                'verbose_name_plural': 'Причины отсутствия',
                'db_table': 'survey_out_reasons',
                'ordering': ['name'],
            },
        ),
    ]
