# Generated by Django 2.2.28 on 2022-05-04 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0201_auto_20220503_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasksExecutionOutReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='tasks/out_reasons/%Y/%m/%d/', verbose_name='Image')),
                ('out_reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_tasksexecutionoutreason_task', to='survey.OutReason', verbose_name='Причина отсутствия')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_tasksexecutionoutreason_task', to='survey.TasksExecution', verbose_name='Task execution')),
            ],
            options={
                'verbose_name': 'Причина отсутствия товара',
                'verbose_name_plural': 'Причины отсутствия товаров',
                'db_table': 'chl_tasks_executions_out_reasons',
                'ordering': ['-task__date_start', 'id'],
            },
        ),
    ]
