# Generated by Django 2.2.28 on 2022-05-04 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0202_tasksexecutionoutreason'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksexecutionoutreason',
            name='good',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='survey_tasksexecutionoutreason_good', to='survey.Good', verbose_name='Good'),
            preserve_default=False,
        ),
    ]
