# Generated by Django 2.2.24 on 2022-05-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0206_auto_20220517_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreason',
            name='is_report',
            field=models.BooleanField(default=False, verbose_name='Отправлять в качестве проблемы'),
        ),
    ]
