# Generated by Django 2.2.24 on 2022-05-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0208_auto_20220526_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='application',
            field=models.CharField(choices=[('iceman', 'Айсмен'), ('classic_logistic', 'Классик логистика'), ('classic_logistic_2', '2 Классик логистика'), ('logistic_msk', 'Логистика МСК'), ('logistic_msk_2', '2 Логистика МСК'), ('nefco', 'Нэфис Косметикс'), ('bp_operators', 'Операторы БП'), ('promotion', 'Продвижение'), ('samberu', 'Самберу'), ('smoroza', 'Смороза Биз'), ('shop_survey', 'Сюрвеер')], default='shop_survey', max_length=20, verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='tasksexecution',
            name='application',
            field=models.CharField(choices=[('iceman', 'Айсмен'), ('classic_logistic', 'Классик логистика'), ('classic_logistic_2', '2 Классик логистика'), ('logistic_msk', 'Логистика МСК'), ('logistic_msk_2', '2 Логистика МСК'), ('nefco', 'Нэфис Косметикс'), ('bp_operators', 'Операторы БП'), ('promotion', 'Продвижение'), ('samberu', 'Самберу'), ('smoroza', 'Смороза Биз'), ('shop_survey', 'Сюрвеер')], default='shop_survey', max_length=20, verbose_name='Проект'),
        ),
    ]
