# Generated by Django 2.2.24 on 2022-05-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0209_auto_20220527_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksexecution',
            name='check',
            field=models.CharField(choices=[('not_checked', 'Ожидает проверки'), ('checked', 'Проверен'), ('not_need', 'Не нужно')], default='not_need', max_length=12, verbose_name='Проверка'),
        ),
    ]
