# Generated by Django 2.2.24 on 2022-05-31 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0210_tasksexecution_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdevice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_device_user', to='survey.User', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='userdeviceiceman',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_device_iceman_user', to='survey.User', verbose_name='User'),
        ),
    ]
