# Generated by Django 2.2.24 on 2022-06-02 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0213_auto_20220601_1701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasksexecutioncheckinspector',
            options={'ordering': ['date_start'], 'verbose_name': 'Task execution', 'verbose_name_plural': 'Проверка выполненных задач'},
        ),
    ]
