# Generated by Django 2.2.24 on 2022-06-17 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0214_auto_20220602_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDelete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Date create')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_delete_user', to='survey.User', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Удаление пользователя',
                'verbose_name_plural': 'Удаление пользователей',
                'db_table': 'telegram_users_deletes',
                'ordering': ['-date_create'],
            },
        ),
    ]
