# Generated by Django 2.2.24 on 2022-06-25 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0215_userdelete'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status_iceman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_status_iceman', to='survey.UserStatus', verbose_name='Статус айсмен'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_status', to='survey.UserStatus', verbose_name='Статус сюрвеер'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_status_agent', to='survey.UserStatus', verbose_name='Статус агент'),
        ),
    ]
