# Generated by Django 2.2.24 on 2022-06-25 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0216_auto_20220625_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatusIceman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=True, verbose_name='Is public')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Статус пользователя Айсмен',
                'verbose_name_plural': 'Статусы пользователей Айсмен',
                'db_table': 'chl_users_statuses_iceman',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='status_iceman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_status_iceman', to='survey.UserStatusIceman', verbose_name='Статус айсмен'),
        ),
    ]
