# Generated by Django 2.2.24 on 2022-07-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0218_userstatusiceman_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdelete',
            name='notification_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата уведомления'),
        ),
        migrations.AddField(
            model_name='userdelete',
            name='notification_send',
            field=models.BooleanField(default=False, verbose_name='Отправлено уведомление'),
        ),
    ]
