# Generated by Django 2.2.28 on 2022-07-13 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0219_auto_20220707_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasksExecutionStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(auto_now_add=True, verbose_name='Date start')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('step_type', models.CharField(choices=[('photos', 'Photos'), ('comment', 'Comment'), ('questionnaire', 'Questionnaire')], default='photos', max_length=20, verbose_name='Step type')),
                ('is_skip', models.BooleanField(default=False, verbose_name='Шаг пропущен')),
                ('order', models.IntegerField(default=1, verbose_name='Сортировка')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_tasksexecutionstep_task', to='survey.TasksExecution', verbose_name='Task execution')),
            ],
            options={
                'verbose_name': 'Шаг выполнения задачи',
                'verbose_name_plural': 'Шаги выполнения задач',
                'db_table': 'chl_tasks_executions_steps',
                'ordering': ['-task__date_start', 'order'],
            },
        ),
    ]
