# Generated by Django 2.2.28 on 2022-07-13 12:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0220_tasksexecutionstep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasksexecutionstep',
            name='date_start',
        ),
        migrations.AddField(
            model_name='tasksexecutionstep',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время выполнения'),
            preserve_default=False,
        ),
    ]
