# Generated by Django 2.2.28 on 2022-07-13 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0221_auto_20220713_1239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasksexecutionstep',
            options={'ordering': ['-task__date_start', 'order'], 'verbose_name': 'Шаг выполнения задачи', 'verbose_name_plural': 'Шаги выполнения задачи'},
        ),
    ]
