# Generated by Django 2.2.28 on 2022-07-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0222_auto_20220713_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasksexecutionstep',
            name='date',
        ),
        migrations.AddField(
            model_name='tasksexecutionstep',
            name='date_end',
            field=models.DateTimeField(verbose_name='Дата завершения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasksexecutionstep',
            name='date_start',
            field=models.DateTimeField(verbose_name='Дата начала'),
            preserve_default=False,
        ),
    ]
