# Generated by Django 2.2.28 on 2022-07-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0224_auto_20220713_1304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasksexecutionstep',
            options={'ordering': ['-task__date_start', 'date_start', 'id'], 'verbose_name': 'Шаг выполнения задачи', 'verbose_name_plural': 'Шаги выполнения задачи'},
        ),
        migrations.AlterField(
            model_name='tasksexecutionstep',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='tasksexecutionstep',
            name='date_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала'),
        ),
    ]
