# Generated by Django 2.2.28 on 2022-07-13 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0225_auto_20220713_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='save_geo',
            field=models.BooleanField(default=False, verbose_name='Отслеживать координаты'),
        ),
        migrations.AddField(
            model_name='user',
            name='save_geo_time',
            field=models.IntegerField(default=5, verbose_name='Периодичность в минутах'),
        ),
        migrations.CreateModel(
            name='UserGeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=True, verbose_name='Is public')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_heo_user', to='survey.User', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Координаты пользователя',
                'verbose_name_plural': 'Координаты пользователей',
                'db_table': 'chl_users_geo',
                'ordering': ['user_id', 'date'],
            },
        ),
    ]
