# Generated by Django 2.2.28 on 2022-07-13 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0226_auto_20220713_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergeo',
            name='is_public',
        ),
    ]
