# Generated by Django 2.2.28 on 2022-07-18 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0227_remove_usergeo_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksexecution',
            name='audit_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_tasksexecution_audit_user', to=settings.AUTH_USER_MODEL, verbose_name='Аудитор задачи'),
        ),
        migrations.AlterField(
            model_name='tasksexecution',
            name='check_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_tasksexecution_check_user', to=settings.AUTH_USER_MODEL, verbose_name='Аудитор причин/чека'),
        ),
    ]
