# Generated by Django 2.2.28 on 2022-07-21 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0229_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=99999999, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sub_user', to='survey.User', verbose_name='User')),
                ('user_sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sub_user_sub', to='survey.User', verbose_name='Подчиненный')),
            ],
            options={
                'verbose_name': 'Подчиненный пользователь',
                'verbose_name_plural': 'Подчиненные пользователи',
                'db_table': 'telegram_users_subs',
                'ordering': ['user', 'order'],
                'unique_together': {('user', 'user_sub')},
            },
        ),
    ]
