# Generated by Django 2.2.28 on 2022-08-10 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_aiproject_is_default'),
        ('survey', '0230_usersub'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ai_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_ai_project', to='ai.AIProject', verbose_name='Проект распознавания'),
        ),
    ]
