# Generated by Django 2.2.28 on 2022-08-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0231_task_ai_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(blank=True, choices=[('default', 'Задание с конструктором'), ('sales', 'Задание продажа'), ('sales_go', 'Задание продажа ГО'), ('sales_go_short', 'Задание продажа ГО сокр.'), ('payment', 'Задание оплата')], max_length=20, null=True, verbose_name='Тип задачи'),
        ),
    ]
