# Generated by Django 2.2.28 on 2022-08-27 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0232_auto_20220821_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(blank=True, choices=[('default', 'Задание с конструктором'), ('sales', 'Задание продажа'), ('sales_go', 'Задание продажа ГО'), ('payment', 'Задание оплата')], max_length=20, null=True, verbose_name='Тип задачи'),
        ),
    ]
