# Generated by Django 2.2.28 on 2022-09-07 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0233_auto_20220827_0111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0, verbose_name='Penalty amount')),
                ('repayment_amount', models.FloatField(default=0, verbose_name='Repayment amount')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Date create')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='survey_penalty_creator', to='survey.User', verbose_name='Creator')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_penalty_user', to='survey.User', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Штраф сюрвеера',
                'verbose_name_plural': 'Штрафы сюрвееров',
                'db_table': 'survey_penalty',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='PenaltyRepayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_te_money', models.FloatField(default=0, verbose_name='Task sum')),
                ('penalty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Penalty', verbose_name='Penalty')),
                ('te', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.TasksExecution', verbose_name='Task execution')),
            ],
            options={
                'verbose_name': 'Погашение штрафа',
                'verbose_name_plural': 'Погашения штрафов',
                'db_table': 'survey_penalty_repayment',
                'ordering': ['penalty'],
            },
        ),
    ]
