# Generated by Django 2.2.28 on 2022-09-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0234_penalty_penaltyrepayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='penaltyrepayment',
            old_name='initial_te_money',
            new_name='repayment_sum',
        ),
        migrations.AlterField(
            model_name='penalty',
            name='amount',
            field=models.FloatField(default=0, verbose_name='Сумма штрафа'),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='repayment_amount',
            field=models.FloatField(default=0, verbose_name='Сумма погашения штрафа'),
        ),
    ]
