# Generated by Django 2.2.28 on 2022-10-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0238_auto_20221007_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='application',
            field=models.CharField(choices=[('iceman', 'Айсмен'), ('promotion', 'ГО Айсмен'), ('classic_logistic', 'Классик логистика'), ('classic_logistic_2', '2 Классик логистика'), ('logistic_msk', 'Логистика МСК'), ('nefco', 'Нэфис Косметикс'), ('samberu', 'Самберу'), ('smoroza', 'Смороза Биз'), ('shop_survey', 'Сюрвеер'), ('logistic_msk_2', 'Сюрвеер СВ'), ('bp_operators', 'Сюрвеер Ш')], default='shop_survey', max_length=20, verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='tasksexecution',
            name='application',
            field=models.CharField(choices=[('iceman', 'Айсмен'), ('promotion', 'ГО Айсмен'), ('classic_logistic', 'Классик логистика'), ('classic_logistic_2', '2 Классик логистика'), ('logistic_msk', 'Логистика МСК'), ('nefco', 'Нэфис Косметикс'), ('samberu', 'Самберу'), ('smoroza', 'Смороза Биз'), ('shop_survey', 'Сюрвеер'), ('logistic_msk_2', 'Сюрвеер СВ'), ('bp_operators', 'Сюрвеер Ш')], default='shop_survey', max_length=20, verbose_name='Проект'),
        ),
    ]
