# Generated by Django 2.2.28 on 2022-10-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0239_auto_20221012_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='storetask',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Последовательность'),
        ),
    ]
