# Generated by Django 2.2.28 on 2022-10-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0240_storetask_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='storetaskavail',
            name='position',
            field=models.IntegerField(blank=True, null=True, verbose_name='Последовательность'),
        ),
        migrations.AlterField(
            model_name='storetask',
            name='position',
            field=models.IntegerField(blank=True, null=True, verbose_name='Последовательность'),
        ),
    ]
