# Generated by Django 2.2.28 on 2022-11-02 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0241_auto_20221015_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevice',
            name='os_version',
            field=models.CharField(default='', max_length=255, verbose_name='Версия ОС'),
        ),
    ]
