# Generated by Django 2.2.28 on 2022-11-02 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0243_tasksexecution_is_fake_gps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksexecution',
            name='is_fake_gps',
            field=models.BooleanField(blank=True, null=True, verbose_name='Подмена GPS'),
        ),
    ]
