# Generated by Django 2.2.28 on 2022-11-08 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0248_auto_20221102_0245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasksexecutioncheckinspector',
            options={'ordering': ['date_start'], 'verbose_name': 'Task execution', 'verbose_name_plural': 'Проверка причин ООS'},
        ),
    ]
